// props/frontend/src/components/stats/DefinitionsTable.tsx
import { Fragment, useMemo, useState } from "react";
import { Table } from "@mantine/core";
import type { DefinitionRow, SplitScopeStats, Split, ExampleKind } from "../../lib/types";
import { formatStatsWithCI, formatAge } from "../../lib/formatters";
import { recallColorClass } from "../../lib/colors";
import DefinitionIdLink from "../../lib/DefinitionIdLink";

interface CellClickInfo {
  definitionId: string;
  split: Split;
  kind: ExampleKind;
}

interface Props {
  definitions: DefinitionRow[];
  exampleCounts?: { [key: string]: { [key: string]: number } };
  onCellClick?: (info: CellClickInfo) => void;
}

function getStats(definition: DefinitionRow, split: Split, kind: ExampleKind): SplitScopeStats | undefined {
  return definition.stats[split]?.[kind];
}

const formatTableAge = (isoDate: string) => formatAge(isoDate, false);
const splits: Split[] = ["valid", "train"];
const kinds: ExampleKind[] = ["whole_snapshot", "file_set"];
const metricsPerKind = 5;

export default function DefinitionsTable({ definitions, exampleCounts, onCellClick }: Props) {
  const [sortColumn, setSortColumn] = useState("valid_whole_snapshot_recall");
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("desc");

  const rows = useMemo(() => {
    const match = /^(valid|train)_(whole_snapshot|file_set)_recall$/.exec(sortColumn);
    return [...definitions].sort((left, right) => {
      let comparison = 0;
      if (sortColumn === "image_digest") {
        comparison = left.image_digest.localeCompare(right.image_digest);
      } else if (sortColumn === "created_at") {
        comparison = left.created_at.localeCompare(right.created_at);
      } else if (match) {
        const [, split, kind] = match;
        comparison =
          (getStats(left, split as Split, kind as ExampleKind)?.recall_stats?.mean ?? -1) -
          (getStats(right, split as Split, kind as ExampleKind)?.recall_stats?.mean ?? -1);
      }
      return sortDirection === "asc" ? comparison : -comparison;
    });
  }, [definitions, sortColumn, sortDirection]);

  function handleSort(columnId: string) {
    if (sortColumn === columnId) {
      setSortDirection((direction) => (direction === "asc" ? "desc" : "asc"));
    } else {
      setSortColumn(columnId);
      setSortDirection("asc");
    }
  }

  function getSortIndicator(columnId: string): string {
    if (sortColumn !== columnId) return "";
    return sortDirection === "asc" ? " ↑" : " ↓";
  }

  function getExampleCount(split: Split, kind: ExampleKind): number {
    return exampleCounts?.[split]?.[kind] ?? 0;
  }

  return (
    <div className="overflow-x-auto">
      <Table horizontalSpacing={0} verticalSpacing={0} className="min-w-full text-sm">
        <Table.Thead>
          <Table.Tr className="border-b border-gray-200 dark:border-gray-700">
            <Table.Th
              rowSpan={3}
              className="px-3 py-2 text-left cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 align-bottom"
              onClick={() => handleSort("image_digest")}
            >
              Definition{getSortIndicator("image_digest")}
            </Table.Th>
            <Table.Th
              rowSpan={3}
              className="px-3 py-2 text-right cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 align-bottom"
              onClick={() => handleSort("created_at")}
            >
              Age{getSortIndicator("created_at")}
            </Table.Th>
            {splits.map((split) => (
              <Table.Th
                key={split}
                colSpan={kinds.length * metricsPerKind}
                className="px-3 py-1 text-center border-l border-gray-300 dark:border-gray-600 font-semibold capitalize"
              >
                {split}
              </Table.Th>
            ))}
          </Table.Tr>
          <Table.Tr className="border-b border-gray-200 dark:border-gray-700">
            {splits.map((split) =>
              kinds.map((kind) => {
                const columnId = `${split}_${kind}_recall`;
                const count = getExampleCount(split, kind);
                return (
                  <Table.Th
                    key={`${split}-${kind}`}
                    colSpan={metricsPerKind}
                    className="px-2 py-1 text-center border-l border-gray-200 dark:border-gray-700 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700"
                    onClick={() => handleSort(columnId)}
                  >
                    {kind} <span className="text-gray-400 dark:text-gray-500 font-normal">(n={count})</span>
                    {getSortIndicator(columnId)}
                  </Table.Th>
                );
              })
            )}
          </Table.Tr>
          <Table.Tr className="border-b border-gray-300 dark:border-gray-600 text-xs text-gray-500 dark:text-gray-400">
            {splits.map((split) =>
              kinds.map((kind) => (
                <Fragment key={`${split}-${kind}`}>
                  <Table.Th className="px-2 py-1 text-right border-l border-gray-200 dark:border-gray-700">
                    Recall
                  </Table.Th>
                  <Table.Th className="px-2 py-1 text-right">Runs</Table.Th>
                  <Table.Th className="px-2 py-1 text-right">Zero</Table.Th>
                  <Table.Th className="px-2 py-1 text-right">Done</Table.Th>
                  <Table.Th className="px-2 py-1 text-right">Stalled</Table.Th>
                </Fragment>
              ))
            )}
          </Table.Tr>
        </Table.Thead>
        <Table.Tbody>
          {rows.map((definition) => (
            <Table.Tr
              key={definition.image_digest}
              className="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800"
            >
              <Table.Td className="px-3 py-2 font-mono text-xs">
                <DefinitionIdLink id={definition.image_digest} display_name={definition.display_name} />
              </Table.Td>
              <Table.Td className="px-3 py-2 text-right text-gray-600 dark:text-gray-400">
                {formatTableAge(definition.created_at)}
              </Table.Td>
              {splits.map((split) =>
                kinds.map((kind) => {
                  const stats = getStats(definition, split, kind);
                  const clickable = onCellClick != null;
                  const clickClass = clickable ? "cursor-pointer hover:bg-blue-100 dark:hover:bg-blue-900" : "";
                  const clickTitle = clickable ? `View ${split} ${kind} runs` : undefined;
                  const handleCellClick = clickable
                    ? () => onCellClick({ definitionId: definition.image_digest, split, kind })
                    : undefined;

                  if (!stats) {
                    const emptyClass = "px-2 py-2 text-right text-gray-300 dark:text-gray-600";
                    return (
                      <Fragment key={`${split}-${kind}`}>
                        <Table.Td
                          className={`${emptyClass} border-l border-gray-100 dark:border-gray-800 ${clickClass}`}
                          onClick={handleCellClick}
                          title={clickTitle}
                        >
                          —
                        </Table.Td>
                        <Table.Td className={emptyClass}>—</Table.Td>
                        <Table.Td className={emptyClass}>—</Table.Td>
                        <Table.Td className={emptyClass}>—</Table.Td>
                        <Table.Td className={emptyClass}>—</Table.Td>
                      </Fragment>
                    );
                  }

                  return (
                    <Fragment key={`${split}-${kind}`}>
                      <Table.Td
                        className={`px-2 py-2 text-right border-l border-gray-100 dark:border-gray-800 ${recallColorClass(
                          stats.recall_stats?.mean
                        )} ${clickClass}`}
                        onClick={handleCellClick}
                        title={clickTitle}
                      >
                        {stats.recall_stats ? formatStatsWithCI(stats.recall_stats) : "—"}
                      </Table.Td>
                      <Table.Td className="px-2 py-2 text-right">{stats.n_examples}</Table.Td>
                      <Table.Td className="px-2 py-2 text-right text-gray-400 dark:text-gray-500">
                        {stats.zero_count}
                      </Table.Td>
                      <Table.Td className="px-2 py-2 text-right">{stats.status_counts.completed ?? 0}</Table.Td>
                      <Table.Td className="px-2 py-2 text-right text-gray-400 dark:text-gray-500">
                        {stats.status_counts.timed_out ?? 0}
                      </Table.Td>
                    </Fragment>
                  );
                })
              )}
            </Table.Tr>
          ))}
        </Table.Tbody>
      </Table>
    </div>
  );
}

// props/specimens/ducktape/2026-05-20-00/code/props/frontend/src/components/stats/DefinitionsTable.svelte
<script lang="ts">
  import { DataTable } from "@careswitch/svelte-data-table";
  import type { DefinitionRow, SplitScopeStats, Split, ExampleKind } from "../../lib/types";
  import { formatStatsWithCI, formatAge } from "../../lib/formatters";
  import { recallColorClass } from "../../lib/colors";
  import DefinitionIdLink from "../../lib/DefinitionIdLink.svelte";

  interface CellClickInfo {
    definitionId: string;
    split: Split;
    kind: ExampleKind;
  }

  interface Props {
    definitions: DefinitionRow[];
    exampleCounts?: { [key: string]: { [key: string]: number } };
    onCellClick?: (_: CellClickInfo) => void;
  }

  let { definitions, exampleCounts, onCellClick }: Props = $props();

  function getStats(def: DefinitionRow, split: Split, kind: ExampleKind): SplitScopeStats | undefined {
    return def.stats[split]?.[kind];
  }

  // Use formatAge from formatters.ts with addSuffix=false for table display
  const formatTableAge = (isoDate: string) => formatAge(isoDate, false);

  function getExampleCount(split: Split, kind: ExampleKind): number {
    return exampleCounts?.[split]?.[kind] ?? 0;
  }

  // Hierarchical structure: splits -> kinds
  const splits: Split[] = ["valid", "train"];
  const kinds: ExampleKind[] = ["whole_snapshot", "file_set"];
  const metricsPerKind = 5; // Recall, Runs, Zero, Done, Stalled

  // Sort state tracked outside DataTable so it survives data changes
  let sortColumn = $state("valid_whole_snapshot_recall");
  let sortDirection: "asc" | "desc" = $state("desc");

  const table = $derived(
    new DataTable({
      data: definitions,
      columns: [
        { id: "image_digest", key: "image_digest", name: "Definition", sortable: true },
        { id: "created_at", key: "created_at", name: "Age", sortable: true },
        // Generate columns for each split/kind combo
        ...splits.flatMap((split) =>
          kinds.map((kind) => ({
            id: `${split}_${kind}_recall`,
            key: "stats" as keyof DefinitionRow,
            name: `${split} ${kind} Recall`,
            sortable: true,
            getValue: (row: DefinitionRow) => getStats(row, split, kind)?.recall_stats?.mean ?? -1,
          }))
        ),
      ],
      initialSort: sortColumn,
      initialSortDirection: sortDirection,
    })
  );

  function handleSort(columnId: string) {
    if (sortColumn === columnId) {
      sortDirection = sortDirection === "asc" ? "desc" : "asc";
    } else {
      sortColumn = columnId;
      sortDirection = "asc";
    }
  }

  function getSortIndicator(columnId: string): string {
    if (sortColumn !== columnId) return "";
    return sortDirection === "asc" ? " ↑" : " ↓";
  }
</script>

<div class="overflow-x-auto">
  <table class="min-w-full text-sm">
    <thead>
      <!-- Level 1: Split (Valid / Train) -->
      <tr class="border-b border-gray-200 dark:border-gray-700">
        <th
          rowspan="3"
          class="px-3 py-2 text-left cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 align-bottom"
          onclick={() => handleSort("image_digest")}
        >
          Definition{getSortIndicator("image_digest")}
        </th>
        <th
          rowspan="3"
          class="px-3 py-2 text-right cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 align-bottom"
          onclick={() => handleSort("created_at")}
        >
          Age{getSortIndicator("created_at")}
        </th>
        {#each splits as split (split)}
          <th
            colspan={kinds.length * metricsPerKind}
            class="px-3 py-1 text-center border-l border-gray-300 dark:border-gray-600 font-semibold capitalize"
          >
            {split}
          </th>
        {/each}
      </tr>
      <!-- Level 2: Kind with example counts -->
      <tr class="border-b border-gray-200 dark:border-gray-700">
        {#each splits as split (split)}
          {#each kinds as kind (`${split}-${kind}`)}
            {@const colId = `${split}_${kind}_recall`}
            {@const count = getExampleCount(split, kind)}
            <th
              colspan={metricsPerKind}
              class="px-2 py-1 text-center border-l border-gray-200 dark:border-gray-700 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700"
              onclick={() => handleSort(colId)}
            >
              {kind} <span class="text-gray-400 dark:text-gray-500 font-normal">(n={count})</span>{getSortIndicator(
                colId
              )}
            </th>
          {/each}
        {/each}
      </tr>
      <!-- Level 3: Metrics -->
      <tr class="border-b border-gray-300 dark:border-gray-600 text-xs text-gray-500 dark:text-gray-400">
        {#each splits as _split (_split)}
          {#each kinds as _kind (`${_split}-${_kind}`)}
            <th class="px-2 py-1 text-right border-l border-gray-200 dark:border-gray-700">Recall</th>
            <th class="px-2 py-1 text-right">Runs</th>
            <th class="px-2 py-1 text-right">Zero</th>
            <th class="px-2 py-1 text-right">Done</th>
            <th class="px-2 py-1 text-right">Stalled</th>
          {/each}
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each table.rows as def (def.image_digest)}
        <tr class="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800">
          <td class="px-3 py-2 font-mono text-xs">
            <DefinitionIdLink id={def.image_digest} display_name={def.display_name} />
          </td>
          <td class="px-3 py-2 text-right text-gray-600 dark:text-gray-400">
            {formatTableAge(def.created_at)}
          </td>
          {#each splits as split (split)}
            {#each kinds as kind (`${split}-${kind}`)}
              {@const stats = getStats(def, split, kind)}
              {@const clickable = onCellClick != null}
              {@const cellClick = clickable
                ? () => onCellClick({ definitionId: def.image_digest, split, kind })
                : undefined}
              {@const clickClass = clickable ? "cursor-pointer hover:bg-blue-100 dark:hover:bg-blue-900" : ""}
              {@const clickTitle = clickable ? `View ${split} ${kind} runs` : undefined}
              {#if stats}
                <td
                  class="px-2 py-2 text-right border-l border-gray-100 dark:border-gray-800 {recallColorClass(
                    stats.recall_stats?.mean
                  )} {clickClass}"
                  onclick={cellClick}
                  title={clickTitle}
                >
                  {stats.recall_stats ? formatStatsWithCI(stats.recall_stats) : "—"}
                </td>
                <td class="px-2 py-2 text-right">{stats.n_examples}</td>
                <td class="px-2 py-2 text-right text-gray-400 dark:text-gray-500">{stats.zero_count}</td>
                <td class="px-2 py-2 text-right">{stats.status_counts.completed ?? 0}</td>
                <td class="px-2 py-2 text-right text-gray-400 dark:text-gray-500"
                  >{stats.status_counts.timed_out ?? 0}</td
                >
              {:else}
                <td
                  class="px-2 py-2 text-right border-l border-gray-100 dark:border-gray-800 text-gray-300 dark:text-gray-600 {clickClass}"
                  onclick={cellClick}
                  title={clickTitle}>—</td
                >
                <td class="px-2 py-2 text-right text-gray-300 dark:text-gray-600">—</td>
                <td class="px-2 py-2 text-right text-gray-300 dark:text-gray-600">—</td>
                <td class="px-2 py-2 text-right text-gray-300 dark:text-gray-600">—</td>
                <td class="px-2 py-2 text-right text-gray-300 dark:text-gray-600">—</td>
              {/if}
            {/each}
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
