// props/frontend/src/lib/CritiqueIssueLink.tsx
import { resolve } from "./router";

interface Props {
  runId: string;
  issueId: string;
  displayText?: string;
}

export default function CritiqueIssueLink({ runId, issueId, displayText }: Props) {
  const text = displayText ?? issueId;

  return (
    <a
      href={resolve(`/runs/${runId}#critique-${issueId}`)}
      className="font-mono text-blue-600 dark:text-blue-400 underline hover:text-blue-800 dark:hover:text-blue-300"
      title={`View critique issue ${issueId} in run ${runId}`}
    >
      {text}
    </a>
  );
}

// props/frontend/src/lib/CritiqueIssueLink.svelte
<script lang="ts">
  import { resolve } from "$lib/router";

  // Link component for critique issue IDs
  // Links to run detail page with anchor to critique issue
  // Uses native <a> with SvelteKit client-side navigation

  interface Props {
    runId: string;
    issueId: string;
    displayText?: string; // Override default issueId display
  }

  const { runId, issueId, displayText }: Props = $props();

  const text = $derived(displayText ?? issueId);
</script>

<a
  href={resolve(`/runs/${runId}#critique-${issueId}`)}
  class="font-mono text-blue-600 dark:text-blue-400 underline hover:text-blue-800 dark:hover:text-blue-300"
  title="View critique issue {issueId} in run {runId}"
>
  {text}
</a>
