// props/frontend/src/lib/FileLink.svelte
<script lang="ts">
  import { resolve } from "$lib/router";

  // Link component for files in snapshots
  // Links to snapshot detail page with file query parameter
  // Uses native <a> with SvelteKit client-side navigation

  interface Props {
    snapshotSlug: string;
    filePath: string;
    displayText?: string; // Override default filePath display
  }

  const { snapshotSlug, filePath, displayText }: Props = $props();

  const text = $derived(displayText ?? filePath);
</script>

<a
  href={resolve(`/snapshots/${snapshotSlug}?file=${encodeURIComponent(filePath)}`)}
  class="font-mono text-xs text-blue-600 dark:text-blue-400 underline hover:text-blue-800 dark:hover:text-blue-300"
  title="View {filePath} in {snapshotSlug}"
>
  {text}
</a>

// props/frontend/src/lib/FileLink.tsx
import { resolve } from "./router";

interface Props {
  snapshotSlug: string;
  filePath: string;
  displayText?: string;
}

export default function FileLink({ snapshotSlug, filePath, displayText }: Props) {
  const text = displayText ?? filePath;

  return (
    <a
      href={resolve(`/snapshots/${snapshotSlug}?file=${encodeURIComponent(filePath)}`)}
      className="font-mono text-xs text-blue-600 dark:text-blue-400 underline hover:text-blue-800 dark:hover:text-blue-300"
      title={`View ${filePath} in ${snapshotSlug}`}
    >
      {text}
    </a>
  );
}
