// props/frontend/src/App.svelte
<script lang="ts">
  import "./app.css";
  import { onMount, setContext } from "svelte";
  import { Toaster } from "svelte-sonner";
  import { pathname, resolve, parseParams } from "$lib/router";
  import { captureTokenFromUrl, getToken, setToken, clearToken, needsToken } from "$lib/stores/token";
  import RunTriggerModal from "$components/RunTriggerModal.svelte";
  import type { Split, ExampleKind } from "$lib/types";

  // Page components
  import OverviewPage from "./pages/OverviewPage.svelte";
  import RunsPage from "./pages/RunsPage.svelte";
  import RunDetailPage from "./pages/RunDetailPage.svelte";
  import DefinitionDetailPage from "./pages/DefinitionDetailPage.svelte";
  import ExamplesPage from "./pages/ExamplesPage.svelte";
  import SnapshotsPage from "./pages/SnapshotsPage.svelte";
  import SnapshotDetailPage from "./pages/SnapshotDetailPage.svelte";

  interface ModalPrefill {
    definitionId?: string;
    split?: Split;
    kind?: ExampleKind;
  }

  let showRunModal = $state(false);
  let modalPrefill: ModalPrefill | undefined = $state(undefined);
  let tokenInput = $state("");
  let usernameInput = $state("");
  let passwordInput = $state("");
  // While true, we're still determining auth (probing for an SSO session cookie),
  // so render neither the login screen nor the app to avoid a flash.
  let checking = $state(true);
  let userEmail = $state<string | null>(null);
  let showTokenLogin = $state(false);
  // False when the backend has no SSO configured (/auth/me 404s) — show the token form directly.
  let ssoAvailable = $state(true);
  // Disable the other mode when one has input
  const tokenHasInput = $derived(tokenInput.trim().length > 0);
  const credsHasInput = $derived(usernameInput.trim().length > 0 || passwordInput.length > 0);

  function handleOpenRunModal(prefill?: ModalPrefill) {
    modalPrefill = prefill;
    showRunModal = true;
  }

  function handleCloseRunModal() {
    showRunModal = false;
    modalPrefill = undefined;
  }

  // Expose modal functions to child components
  setContext("runModal", { open: handleOpenRunModal });

  function handleLogin() {
    const token = tokenInput.trim();
    const user = usernameInput.trim();
    const pass = passwordInput;

    if (token) {
      setToken(token);
      tokenInput = "";
    } else if (user && pass) {
      setToken(btoa(`${user}:${pass}`));
      usernameInput = "";
      passwordInput = "";
    } else {
      return;
    }
  }

  async function handleLogout() {
    clearToken();
    // Clear the server-side SSO session too (no-op/404 when SSO is disabled).
    await fetch("/auth/logout", { credentials: "include" }).catch(() => undefined);
    window.location.href = "/";
  }

  async function initAuth() {
    captureTokenFromUrl();
    if (getToken()) {
      needsToken.set(false);
      return;
    }
    // No stored token: check for a valid Authentik SSO session cookie.
    try {
      const resp = await fetch("/auth/me", { credentials: "include" });
      if (resp.ok) {
        const data = (await resp.json()) as { email: string };
        userEmail = data.email;
        needsToken.set(false);
      } else {
        if (resp.status === 404) {
          // SSO not configured on the backend: skip the SSO button, show the token form.
          ssoAvailable = false;
          showTokenLogin = true;
        }
        needsToken.set(true);
      }
    } catch {
      needsToken.set(true);
    }
  }

  onMount(() => {
    initAuth().finally(() => {
      checking = false;
    });
  });

  // Navigation items
  const navItems = [
    { path: "/", label: "Overview" },
    { path: "/runs", label: "Runs" },
    { path: "/snapshots", label: "Ground Truth" },
  ];

  function isActive(path: string, currentPath: string): boolean {
    if (path === "/") return currentPath === "/";
    return currentPath.startsWith(path);
  }

  // Route matching — $pathname is already the clean path (no query string).
  const currentRoute = $derived.by(() => {
    const path = $pathname;

    // Match routes in order of specificity
    let params: Record<string, string> | null;

    // /runs/:runId
    params = parseParams("/runs/[runId]", path);
    if (params) return { component: "run-detail", params };

    // /runs
    if (path === "/runs") return { component: "runs", params: {} };

    // /definitions/:definitionId
    params = parseParams("/definitions/[definitionId]", path);
    if (params) return { component: "definition-detail", params };

    // /examples
    if (path === "/examples") return { component: "examples", params: {} };

    // /snapshots/:slug (catch-all for nested paths)
    params = parseParams("/snapshots/[...slug]", path);
    if (params) return { component: "snapshot-detail", params };

    // /snapshots
    if (path === "/snapshots") return { component: "snapshots", params: {} };

    // / (home)
    if (path === "/" || path === "") return { component: "overview", params: {} };

    // 404
    return { component: "not-found", params: {} };
  });
</script>

<Toaster richColors position="top-right" duration={8000} />

{#if checking}
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
    <div class="text-sm text-gray-500 dark:text-gray-400">Loading…</div>
  </div>
{:else if $needsToken}
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md dark:shadow-gray-950/50 p-8 max-w-md w-full">
      <h1 class="text-xl font-bold mb-4">Props</h1>
      {#if ssoAvailable}
        <a
          href="/auth/login"
          class="block w-full text-center px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700"
        >
          Sign in with Authentik
        </a>
      {/if}
      {#if showTokenLogin}
        {#if ssoAvailable}
          <div class="flex items-center gap-2 my-4">
            <div class="flex-1 border-t border-gray-200 dark:border-gray-700"></div>
            <span class="text-xs text-gray-400 dark:text-gray-500">or use a token</span>
            <div class="flex-1 border-t border-gray-200 dark:border-gray-700"></div>
          </div>
        {/if}
        <form
          onsubmit={(e: SubmitEvent) => {
            e.preventDefault();
            handleLogin();
          }}
          class="flex flex-col gap-3"
        >
          <div class="flex flex-col gap-2 transition-opacity {tokenHasInput ? 'opacity-40' : ''}">
            <input
              type="text"
              bind:value={usernameInput}
              placeholder="Username"
              autocomplete="username"
              disabled={tokenHasInput}
              class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100 dark:disabled:bg-gray-800 disabled:cursor-not-allowed"
            />
            <input
              type="password"
              bind:value={passwordInput}
              placeholder="Password"
              autocomplete="current-password"
              disabled={tokenHasInput}
              class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100 dark:disabled:bg-gray-800 disabled:cursor-not-allowed"
            />
          </div>
          <div class="flex items-center gap-2">
            <div class="flex-1 border-t border-gray-200 dark:border-gray-700"></div>
            <span class="text-xs text-gray-400 dark:text-gray-500">or token</span>
            <div class="flex-1 border-t border-gray-200 dark:border-gray-700"></div>
          </div>
          <div class="transition-opacity {credsHasInput ? 'opacity-40' : ''}">
            <input
              type="text"
              bind:value={tokenInput}
              placeholder="base64 token"
              disabled={credsHasInput}
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100 dark:disabled:bg-gray-800 disabled:cursor-not-allowed"
            />
          </div>
          <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded text-sm font-medium hover:bg-blue-700">
            Sign in
          </button>
        </form>
      {:else}
        <button
          type="button"
          onclick={() => (showTokenLogin = true)}
          class="mt-3 block w-full text-center text-xs text-gray-500 dark:text-gray-400 hover:underline"
        >
          Use a token instead
        </button>
      {/if}
    </div>
  </div>
{:else}
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900">
    <!-- Header -->
    <header class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-6 py-3">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <h1 class="text-xl font-bold">
            <a href={resolve("/")} class="hover:text-blue-600">Props</a>
          </h1>
        </div>
        <nav class="flex gap-1">
          {#each navItems as { path, label } (path)}
            <a
              href={resolve(path)}
              class="px-3 py-1.5 rounded text-sm font-medium transition-colors
                {isActive(path, $pathname)
                ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300'
                : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-gray-100'}"
            >
              {label}
            </a>
          {/each}
        </nav>
        <div class="flex items-center gap-3">
          {#if userEmail}
            <span class="text-xs text-gray-500 dark:text-gray-400">{userEmail}</span>
          {/if}
          <button
            type="button"
            onclick={handleLogout}
            class="px-3 py-1.5 rounded text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
          >
            Logout
          </button>
        </div>
      </div>
    </header>

    <!-- Main content -->
    <main class="p-6">
      {#if currentRoute.component === "overview"}
        <OverviewPage />
      {:else if currentRoute.component === "runs"}
        <RunsPage />
      {:else if currentRoute.component === "run-detail"}
        <RunDetailPage runId={currentRoute.params.runId} />
      {:else if currentRoute.component === "definition-detail"}
        <DefinitionDetailPage definitionId={currentRoute.params.definitionId} />
      {:else if currentRoute.component === "examples"}
        <ExamplesPage />
      {:else if currentRoute.component === "snapshots"}
        <SnapshotsPage />
      {:else if currentRoute.component === "snapshot-detail"}
        <SnapshotDetailPage slug={currentRoute.params.slug} />
      {:else}
        <div class="text-center py-12">
          <h2 class="text-2xl font-bold text-gray-900 dark:text-gray-100">Page Not Found</h2>
          <p class="mt-2 text-gray-600 dark:text-gray-400">The page you're looking for doesn't exist.</p>
          <a href={resolve("/")} class="mt-4 inline-block text-blue-600 dark:text-blue-400 hover:underline">Go home</a>
        </div>
      {/if}
    </main>
  </div>

  <RunTriggerModal open={showRunModal} onClose={handleCloseRunModal} prefill={modalPrefill} />
{/if}

// props/frontend/src/App.tsx
import {
  Anchor,
  AppShell,
  Button,
  Center,
  Divider,
  Group,
  MantineProvider,
  Paper,
  PasswordInput,
  Stack,
  Text,
  TextInput,
  Title,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { useEffect, useMemo, useState, type FormEvent, type JSX, type ReactNode } from "react";

import RunTriggerModal from "$components/RunTriggerModal";
import { parseParams, resolve, useRoute } from "$lib/router";
import { RunModalContext } from "$lib/runModalContext";
import {
  clearToken,
  captureTokenFromUrl,
  getToken,
  markSessionAuthenticated,
  setToken,
  useNeedsToken,
} from "$lib/stores/token";
import type { RunModalPrefill } from "$lib/types";
import DefinitionDetailPage from "./pages/DefinitionDetailPage";
import ExamplesPage from "./pages/ExamplesPage";
import OverviewPage from "./pages/OverviewPage";
import RunDetailPage from "./pages/RunDetailPage";
import RunsPage from "./pages/RunsPage";
import SnapshotDetailPage from "./pages/SnapshotDetailPage";
import SnapshotsPage from "./pages/SnapshotsPage";

const navItems = [
  { path: "/", label: "Overview" },
  { path: "/runs", label: "Runs" },
  { path: "/snapshots", label: "Ground Truth" },
];

function isActive(path: string, currentPath: string): boolean {
  return path === "/" ? currentPath === "/" : currentPath.startsWith(path);
}

type CurrentRoute =
  | { component: "overview" | "runs" | "examples" | "snapshots" }
  | { component: "run-detail"; runId: string }
  | { component: "definition-detail"; definitionId: string }
  | { component: "snapshot-detail"; slug: string }
  | { component: "not-found" };

function matchRoute(path: string): CurrentRoute {
  const run = parseParams("/runs/[runId]", path);
  if (run) return { component: "run-detail", runId: run.runId };
  if (path === "/runs") return { component: "runs" };

  const definition = parseParams("/definitions/[definitionId]", path);
  if (definition) return { component: "definition-detail", definitionId: definition.definitionId };
  if (path === "/examples") return { component: "examples" };

  const snapshot = parseParams("/snapshots/[...slug]", path);
  if (snapshot) return { component: "snapshot-detail", slug: snapshot.slug };
  if (path === "/snapshots") return { component: "snapshots" };
  if (path === "/" || path === "") return { component: "overview" };
  return { component: "not-found" };
}

function PropsApp(): JSX.Element {
  const { pathname } = useRoute();
  const needsToken = useNeedsToken();
  const route = useMemo(() => matchRoute(pathname), [pathname]);
  const [showRunModal, setShowRunModal] = useState(false);
  const [modalPrefill, setModalPrefill] = useState<RunModalPrefill | undefined>();
  const [tokenInput, setTokenInput] = useState("");
  const [usernameInput, setUsernameInput] = useState("");
  const [passwordInput, setPasswordInput] = useState("");
  const [checking, setChecking] = useState(true);
  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [showTokenLogin, setShowTokenLogin] = useState(false);
  const [ssoAvailable, setSsoAvailable] = useState(true);

  const tokenHasInput = tokenInput.trim().length > 0;
  const credsHaveInput = usernameInput.trim().length > 0 || passwordInput.length > 0;

  useEffect(() => {
    let alive = true;
    async function initAuth(): Promise<void> {
      captureTokenFromUrl();
      if (getToken()) return;

      try {
        const response = await fetch("/auth/me", { credentials: "include" });
        if (!alive) return;
        if (response.ok) {
          const data = (await response.json()) as { email: string };
          setUserEmail(data.email);
          markSessionAuthenticated();
        } else if (response.status === 404) {
          setSsoAvailable(false);
          setShowTokenLogin(true);
        }
      } catch {
        // The token form remains available if SSO discovery is unreachable.
      }
    }

    void initAuth().finally(() => {
      if (alive) setChecking(false);
    });
    return () => {
      alive = false;
    };
  }, []);

  function handleOpenRunModal(prefill?: RunModalPrefill): void {
    setModalPrefill(prefill);
    setShowRunModal(true);
  }

  function handleCloseRunModal(): void {
    setShowRunModal(false);
    setModalPrefill(undefined);
  }

  function handleLogin(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    const token = tokenInput.trim();
    const username = usernameInput.trim();
    if (token) {
      setToken(token);
      setTokenInput("");
    } else if (username && passwordInput) {
      setToken(btoa(`${username}:${passwordInput}`));
      setUsernameInput("");
      setPasswordInput("");
    }
  }

  async function handleLogout(): Promise<void> {
    clearToken();
    await fetch("/auth/logout", { credentials: "include" }).catch(() => undefined);
    window.location.href = "/";
  }

  const runModal = useMemo(() => ({ open: handleOpenRunModal }), []);

  if (checking) {
    return (
      <Center className="min-h-screen bg-gray-50 dark:bg-gray-900">
        <Stack align="center" gap="sm">
          <div className="text-sm text-gray-500 dark:text-gray-400">Loading…</div>
        </Stack>
      </Center>
    );
  }

  if (needsToken) {
    return (
      <Center className="min-h-screen bg-gray-50 dark:bg-gray-900 px-4">
        <Paper shadow="md" radius="md" p="xl" className="w-full max-w-md dark:bg-gray-800">
          <Stack gap="md">
            <Title order={2}>Props</Title>
            {ssoAvailable && (
              <Button component="a" href="/auth/login" fullWidth>
                Sign in with Authentik
              </Button>
            )}
            {showTokenLogin ? (
              <>
                {ssoAvailable && (
                  <Group gap="sm" wrap="nowrap">
                    <Divider className="flex-1" />
                    <Text size="xs" c="dimmed" style={{ whiteSpace: "nowrap" }}>
                      or use a token
                    </Text>
                    <Divider className="flex-1" />
                  </Group>
                )}
                <form onSubmit={handleLogin}>
                  <Stack gap="sm">
                    <Stack gap="xs" className={tokenHasInput ? "opacity-40" : ""}>
                      <TextInput
                        placeholder="Username"
                        autoComplete="username"
                        disabled={tokenHasInput}
                        value={usernameInput}
                        onChange={(event) => setUsernameInput(event.currentTarget.value)}
                      />
                      <PasswordInput
                        placeholder="Password"
                        autoComplete="current-password"
                        disabled={tokenHasInput}
                        value={passwordInput}
                        onChange={(event) => setPasswordInput(event.currentTarget.value)}
                      />
                    </Stack>
                    <Group gap="sm" wrap="nowrap">
                      <Divider className="flex-1" />
                      <Text size="xs" c="dimmed" style={{ whiteSpace: "nowrap" }}>
                        or token
                      </Text>
                      <Divider className="flex-1" />
                    </Group>
                    <TextInput
                      placeholder="base64 token"
                      disabled={credsHaveInput}
                      className={credsHaveInput ? "opacity-40" : ""}
                      value={tokenInput}
                      onChange={(event) => setTokenInput(event.currentTarget.value)}
                    />
                    <Button type="submit">Sign in</Button>
                  </Stack>
                </form>
              </>
            ) : (
              <Button variant="subtle" color="gray" onClick={() => setShowTokenLogin(true)}>
                Use a token instead
              </Button>
            )}
          </Stack>
        </Paper>
      </Center>
    );
  }

  let page: ReactNode;
  switch (route.component) {
    case "overview":
      page = <OverviewPage />;
      break;
    case "runs":
      page = <RunsPage />;
      break;
    case "run-detail":
      page = <RunDetailPage runId={route.runId} />;
      break;
    case "definition-detail":
      page = <DefinitionDetailPage definitionId={route.definitionId} />;
      break;
    case "examples":
      page = <ExamplesPage />;
      break;
    case "snapshots":
      page = <SnapshotsPage />;
      break;
    case "snapshot-detail":
      page = <SnapshotDetailPage slug={route.slug} />;
      break;
    default:
      page = (
        <Center py={80}>
          <Stack align="center" gap="xs">
            <Title order={2}>Page Not Found</Title>
            <Text c="dimmed">The page you&apos;re looking for doesn&apos;t exist.</Text>
            <Button component="a" href={resolve("/")} variant="subtle">
              Go home
            </Button>
          </Stack>
        </Center>
      );
  }

  return (
    <RunModalContext.Provider value={runModal}>
      <AppShell header={{ height: 60 }}>
        <AppShell.Header px="md" className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
          <Group h="100%" justify="space-between" wrap="nowrap">
            <Title order={3} m={0}>
              <Anchor href={resolve("/")} c="inherit" underline="never">
                Props
              </Anchor>
            </Title>
            <Group component="nav" gap={4}>
              {navItems.map(({ path, label }) => (
                <Button
                  key={path}
                  component="a"
                  href={resolve(path)}
                  size="sm"
                  variant={isActive(path, pathname) ? "light" : "subtle"}
                >
                  {label}
                </Button>
              ))}
            </Group>
            <Group gap="sm">
              {userEmail && (
                <Text size="xs" c="dimmed">
                  {userEmail}
                </Text>
              )}
              <Button variant="subtle" color="gray" size="sm" onClick={() => void handleLogout()}>
                Logout
              </Button>
            </Group>
          </Group>
        </AppShell.Header>
        <AppShell.Main className="bg-gray-50 dark:bg-gray-900 p-6">{page}</AppShell.Main>
      </AppShell>
      <RunTriggerModal open={showRunModal} onClose={handleCloseRunModal} prefill={modalPrefill} />
    </RunModalContext.Provider>
  );
}

export default function App(): JSX.Element {
  return (
    <MantineProvider defaultColorScheme="auto">
      <Notifications position="top-right" autoClose={8000} />
      <PropsApp />
    </MantineProvider>
  );
}
