// props/frontend/src/components/Breadcrumb.svelte
<script lang="ts">
  import { ChevronRight } from "lucide-svelte";
  import { resolve } from "$lib/router";

  interface BreadcrumbItem {
    label: string;
    href?: string;
  }

  interface Props {
    items: BreadcrumbItem[];
  }

  const { items }: Props = $props();
</script>

<nav class="flex items-center gap-1 text-sm text-gray-600 dark:text-gray-400">
  {#each items as item, i (i)}
    {#if i > 0}
      <ChevronRight size={16} class="text-gray-400 dark:text-gray-500" />
    {/if}
    {#if item.href}
      <a href={resolve(item.href)} class="hover:text-gray-900 dark:hover:text-gray-100 hover:underline">
        {item.label}
      </a>
    {:else}
      <span class="text-gray-900 dark:text-gray-100 font-medium">{item.label}</span>
    {/if}
  {/each}
</nav>

// props/frontend/src/components/Breadcrumb.tsx
import { Fragment } from "react";
import { ChevronRight } from "../lib/icons";
import { resolve } from "../lib/router";

interface BreadcrumbItem {
  label: string;
  href?: string;
}

interface Props {
  items: BreadcrumbItem[];
}

export default function Breadcrumb({ items }: Props) {
  return (
    <nav className="flex items-center gap-1 text-sm text-gray-600 dark:text-gray-400">
      {items.map((item, index) => (
        <Fragment key={index}>
          {index > 0 && <ChevronRight size={16} className="text-gray-400 dark:text-gray-500" />}
          {item.href ? (
            <a href={resolve(item.href)} className="hover:text-gray-900 dark:hover:text-gray-100 hover:underline">
              {item.label}
            </a>
          ) : (
            <span className="text-gray-900 dark:text-gray-100 font-medium">{item.label}</span>
          )}
        </Fragment>
      ))}
    </nav>
  );
}
