// props/frontend/src/components/TabButton.tsx
import type { ReactNode } from "react";
import { Button } from "@mantine/core";

interface Props {
  active: boolean;
  onClick: () => void;
  children: ReactNode;
}

export default function TabButton({ active, onClick, children }: Props) {
  return (
    <Button
      unstyled
      type="button"
      className={`px-4 py-2 font-medium text-sm border-b-2 ${
        active
          ? "border-blue-500 text-blue-600 dark:text-blue-400"
          : "border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300"
      }`}
      onClick={onClick}
    >
      {children}
    </Button>
  );
}

// props/frontend/src/components/TabButton.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    active: boolean;
    onclick: () => void;
    children: Snippet;
  }

  const { active, onclick, children }: Props = $props();
</script>

<button
  type="button"
  class="px-4 py-2 font-medium text-sm border-b-2 {active
    ? 'border-blue-500 text-blue-600 dark:text-blue-400'
    : 'border-transparent text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'}"
  {onclick}
>
  {@render children()}
</button>
