// airlock/frontend/App.tsx
import { Anchor, Badge, Box, Container, Group, Stack, Text, Title } from "@mantine/core";
import { type JSX, useEffect, useState } from "react";

import { getApiClient } from "./api";
import type { DeploymentInfo } from "./types";
import { OAuthProviders } from "./OAuthProviders";

export default function App(): JSX.Element {
  const [deploymentInfo, setDeploymentInfo] = useState<DeploymentInfo | null>(null);

  useEffect(() => {
    void getApiClient()
      .getDeploymentInfo()
      .then(setDeploymentInfo)
      .catch((error: unknown) => {
        console.error("Failed to load Airlock deployment info", error);
      });
  }, []);

  return (
    <Stack gap={0} mih="100vh">
      <Box component="header" style={{ backgroundColor: "#073642" }}>
        <Container size="lg" py="md">
          <Group>
            <Stack gap={0}>
              <Title order={1} size="h3" c="white">
                Airlock
              </Title>
              <Text size="sm" c="gray.3">
                OAuth credential broker
              </Text>
            </Stack>
          </Group>
        </Container>
      </Box>

      <Container component="main" size="lg" py="xl" style={{ flex: 1 }}>
        <OAuthProviders />
      </Container>

      {deploymentInfo && (deploymentInfo.image_tag || deploymentInfo.source_commit) && (
        <Container component="footer" size="lg" py="md">
          <Group justify="center" gap="xs" wrap="wrap">
            <Text size="xs" c="dimmed">
              Deployed commit
            </Text>
            {deploymentInfo.source_commit_url ? (
              <Anchor
                href={deploymentInfo.source_commit_url}
                target="_blank"
                rel="noreferrer"
                size="xs"
                ff="monospace"
                title={deploymentInfo.source_commit ?? undefined}
              >
                {deploymentInfo.source_commit?.slice(0, 7) ?? "unknown"}
              </Anchor>
            ) : (
              <Text size="xs" ff="monospace" c="dimmed">
                {deploymentInfo.source_commit?.slice(0, 7) ?? "unknown"}
              </Text>
            )}
            {deploymentInfo.image_tag && (
              <Badge variant="light" color="gray" title={deploymentInfo.image_tag}>
                {deploymentInfo.image_tag}
              </Badge>
            )}
          </Group>
        </Container>
      )}
    </Stack>
  );
}

// airlock/frontend/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { getApiClient } from "./api.ts";
  import OAuthProviders from "./OAuthProviders.svelte";
  import type { DeploymentInfo } from "./types.ts";

  let deploymentInfo = $state<DeploymentInfo | null>(null);

  onMount(async () => {
    try {
      deploymentInfo = await getApiClient().getDeploymentInfo();
    } catch (error) {
      console.error("Failed to load Airlock deployment info", error);
    }
  });
</script>

<header class="app-header px-4 py-3 sm:px-6 flex items-baseline gap-3">
  <h1 class="app-header-title text-lg font-semibold m-0">Airlock</h1>
  <span class="app-header-subtitle text-sm">OAuth credential broker</span>
</header>

<main class="max-w-4xl mx-auto px-4 py-6">
  <OAuthProviders />
</main>

{#if deploymentInfo?.image_tag || deploymentInfo?.source_commit}
  <footer class="app-footer max-w-4xl mx-auto px-4 py-4 text-xs flex flex-wrap justify-center gap-2">
    <span style="color: var(--color-text-muted);">Deployed commit</span>
    {#if deploymentInfo.source_commit_url}
      <a
        href={deploymentInfo.source_commit_url}
        target="_blank"
        rel="noreferrer"
        class="font-mono"
        style="color: var(--color-link);"
      >
        {deploymentInfo.source_commit?.slice(0, 7) ?? "unknown"}
      </a>
    {:else}
      <span class="font-mono" style="color: var(--color-text-muted);">
        {deploymentInfo.source_commit?.slice(0, 7) ?? "unknown"}
      </span>
    {/if}
    {#if deploymentInfo.image_tag}
      <span class="font-mono" title={deploymentInfo.image_tag} style="color: var(--color-text-muted); opacity: 0.65;">
        {deploymentInfo.image_tag}
      </span>
    {/if}
  </footer>
{/if}
