// airlock/frontend/OAuthProviders.svelte
<script lang="ts">
  import { getApiClient } from "./api.ts";
  import type { OAuthProviderStatus } from "./types.ts";
  import { onMount } from "svelte";

  let providers = $state<OAuthProviderStatus[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);

  type ScopeRow = {
    scope: string;
    requested: boolean;
    granted: boolean;
  };
  type ScopeComparison = {
    rows: ScopeRow[];
    missing: string[];
    extra: string[];
    drift: boolean;
  };

  onMount(async () => {
    try {
      const api = await getApiClient();
      providers = await api.listOAuthProviders();
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  });

  function fmtExpiry(iso: string | null): string {
    if (!iso) return "N/A";
    return new Date(iso).toLocaleString();
  }

  function compareScopes(requested: string[], granted: string): ScopeComparison {
    const requestedScopes = [...new Set(requested)];
    const requestedSet = new Set(requestedScopes);
    const grantedSet = new Set(granted ? granted.split(/\s+/).filter(Boolean) : []);
    const missing = requestedScopes.filter((scope) => !grantedSet.has(scope)).sort();
    const extra = [...grantedSet].filter((scope) => !requestedSet.has(scope)).sort();
    return {
      rows: [...requestedScopes, ...extra].map((scope) => ({
        scope,
        requested: requestedSet.has(scope),
        granted: grantedSet.has(scope),
      })),
      missing,
      extra,
      drift: missing.length + extra.length > 0,
    };
  }
</script>

<h2 class="section-heading text-xs font-semibold uppercase tracking-wider mb-3">OAuth Providers</h2>

{#if loading}
  <p class="section-heading italic py-4">Loading providers…</p>
{:else if error}
  <p class="font-medium" style="color: var(--color-error);">Failed to load providers: {error}</p>
{:else if providers.length === 0}
  <p class="section-heading italic py-4">No OAuth providers configured.</p>
{:else}
  <div class="space-y-4">
    {#each providers as provider (provider.name)}
      {@const grantedScope =
        provider.status.state === "connected" || provider.status.state === "expired" ? provider.status.scope : ""}
      {@const scopes = compareScopes(provider.requested_scopes, grantedScope)}
      <div class="card rounded-lg shadow-sm p-5">
        <div class="flex items-start justify-between gap-4">
          <div class="flex-1">
            <h3 class="text-sm font-semibold m-0" style="color: var(--color-text);">{provider.display_name}</h3>
            <dl class="grid grid-cols-1 sm:grid-cols-[120px_1fr] gap-x-4 gap-y-1 text-sm mt-3">
              <dt class="section-heading font-semibold">Type</dt>
              <dd class="m-0"><code class="code-tag text-xs rounded px-1.5 py-0.5">{provider.provider_type}</code></dd>
              <dt class="section-heading font-semibold">Status</dt>
              <dd class="m-0">
                {#if provider.status.state === "connected"}
                  <span class="status-pill status-pill-connected">Connected</span>
                {:else if provider.status.state === "expired"}
                  <span class="status-pill status-pill-expired">Token expired — refresh failing</span>
                {:else}
                  <span class="status-pill status-pill-disconnected">Not connected</span>
                {/if}
              </dd>
              <dt class="section-heading font-semibold">Scopes</dt>
              <dd class="m-0 min-w-0">
                <div class="scope-table-wrap overflow-x-auto rounded-md">
                  <table class="scope-table min-w-full border-collapse text-xs">
                    <thead>
                      <tr class="thead-row">
                        <th class="th-cell px-3 py-2 text-left font-semibold">Scope</th>
                        <th class="th-cell px-3 py-2 text-center font-semibold">Requested</th>
                        <th class="th-cell px-3 py-2 text-center font-semibold">Granted</th>
                      </tr>
                    </thead>
                    <tbody class="tbody">
                      {#if scopes.rows.length === 0}
                        <tr>
                          <td class="px-3 py-2 italic" colspan="3" style="color: var(--color-text-muted);">No scopes</td
                          >
                        </tr>
                      {:else}
                        {#each scopes.rows as row (row.scope)}
                          <tr class="data-row">
                            <td class="scope-cell px-3 py-2 font-mono">{row.scope}</td>
                            <td class="px-3 py-2 text-center">
                              <span class={row.requested ? "scope-mark scope-mark-yes" : "scope-mark scope-mark-no"}>
                                {row.requested ? "✓" : "✕"}
                              </span>
                            </td>
                            <td class="px-3 py-2 text-center">
                              <span class={row.granted ? "scope-mark scope-mark-yes" : "scope-mark scope-mark-no"}>
                                {row.granted ? "✓" : "✕"}
                              </span>
                            </td>
                          </tr>
                        {/each}
                      {/if}
                    </tbody>
                  </table>
                </div>
              </dd>
              {#if provider.status.state === "connected" || provider.status.state === "expired"}
                <dt class="section-heading font-semibold">Access token</dt>
                <dd class="m-0" style="color: var(--color-text-muted);">
                  {provider.status.state === "expired"
                    ? `Expired ${fmtExpiry(provider.status.expires_at)}`
                    : `Expires ${fmtExpiry(provider.status.expires_at)}`}
                </dd>
                {#if scopes.drift}
                  <dt class="section-heading font-semibold">Drift</dt>
                  <dd class="m-0" style="color: var(--color-warning, #b45309);">
                    {#if scopes.missing.length > 0}missing: <code class="code-tag text-xs rounded px-1.5 py-0.5"
                        >{scopes.missing.join(" ")}</code
                      >{/if}
                    {#if scopes.missing.length > 0 && scopes.extra.length > 0}<span>; </span>{/if}
                    {#if scopes.extra.length > 0}extra: <code class="code-tag text-xs rounded px-1.5 py-0.5"
                        >{scopes.extra.join(" ")}</code
                      >{/if}
                    — re-authorize to fix
                  </dd>
                {/if}
                {#if provider.status.state === "expired" && provider.status.last_refresh_error}
                  <dt class="section-heading font-semibold">Refresh error</dt>
                  <dd class="m-0">
                    <code
                      class="code-tag text-xs rounded px-1.5 py-0.5 block whitespace-pre-wrap"
                      style="color: var(--color-error);">{provider.status.last_refresh_error}</code
                    >
                  </dd>
                {/if}
              {/if}
            </dl>
          </div>
          <a
            href="/oauth/authorize/{provider.name}"
            class="btn-primary font-semibold px-5 py-2.5 rounded-lg border-0 cursor-pointer transition-colors text-sm no-underline"
          >
            {provider.status.state === "connected" ? "Reconnect" : "Connect"}
          </a>
        </div>
      </div>
    {/each}
  </div>
{/if}

<style>
  .scope-table-wrap {
    border: 1px solid var(--color-border);
  }

  .scope-cell {
    color: var(--color-text-code);
    overflow-wrap: anywhere;
  }

  .scope-mark {
    font-weight: 700;
  }

  .scope-mark-yes {
    color: var(--color-success);
  }

  .scope-mark-no {
    color: var(--color-text-muted);
  }
</style>

// airlock/frontend/OAuthProviders.tsx
import {
  Alert,
  Badge,
  Box,
  Button,
  Code,
  Divider,
  Group,
  Loader,
  Paper,
  SimpleGrid,
  Stack,
  Table,
  Text,
  Title,
} from "@mantine/core";
import { type JSX, useEffect, useState } from "react";

import { getApiClient } from "./api";
import type { OAuthProviderStatus } from "./types";

type ScopeRow = {
  scope: string;
  requested: boolean;
  granted: boolean;
};

type ScopeComparison = {
  rows: ScopeRow[];
  missing: string[];
  extra: string[];
  drift: boolean;
};

function compareScopes(requested: string[], granted: string): ScopeComparison {
  const requestedScopes = [...new Set(requested)];
  const requestedSet = new Set(requestedScopes);
  const grantedSet = new Set(granted ? granted.split(/\s+/).filter(Boolean) : []);
  const missing = requestedScopes.filter((scope) => !grantedSet.has(scope)).sort();
  const extra = [...grantedSet].filter((scope) => !requestedSet.has(scope)).sort();

  return {
    rows: [...requestedScopes, ...extra].map((scope) => ({
      scope,
      requested: requestedSet.has(scope),
      granted: grantedSet.has(scope),
    })),
    missing,
    extra,
    drift: missing.length + extra.length > 0,
  };
}

function ProviderStatusBadge({ provider }: { provider: OAuthProviderStatus }): JSX.Element {
  switch (provider.status.state) {
    case "connected":
      return <Badge color="green">Connected</Badge>;
    case "expired":
      return <Badge color="red">Token expired — refresh failing</Badge>;
    case "disconnected":
      return <Badge color="yellow">Not connected</Badge>;
    default:
      return <Badge color="gray">Unknown status</Badge>;
  }
}

function formatExpiry(iso: string): string {
  return new Date(iso).toLocaleString();
}

function ProviderCard({ provider }: { provider: OAuthProviderStatus }): JSX.Element {
  const tokenStatus =
    provider.status.state === "connected" || provider.status.state === "expired" ? provider.status : null;
  const grantedScope = tokenStatus?.scope ?? "";
  const scopes = compareScopes(provider.requested_scopes, grantedScope);

  return (
    <Paper withBorder radius="md" p="lg">
      <Stack gap="md">
        <Group justify="space-between" align="flex-start">
          <Stack gap="xs" style={{ minWidth: 0 }}>
            <Group gap="sm">
              <Title order={3} size="h4">
                {provider.display_name}
              </Title>
              <Badge variant="outline" color="gray">
                {provider.provider_type}
              </Badge>
            </Group>
            <Group gap="xs">
              <Text size="sm" c="dimmed">
                Status
              </Text>
              <ProviderStatusBadge provider={provider} />
            </Group>
          </Stack>
          <Button component="a" href={"/oauth/authorize/" + provider.name} style={{ flexShrink: 0 }}>
            {provider.status.state === "connected" ? "Reconnect" : "Connect"}
          </Button>
        </Group>

        <Divider />

        <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="md">
          <Stack gap={4}>
            <Text size="xs" fw={600} c="dimmed">
              Requested scopes
            </Text>
            <Code style={{ overflowWrap: "anywhere" }}>
              {provider.requested_scopes.length > 0 ? provider.requested_scopes.join(" ") : "None"}
            </Code>
          </Stack>
          {tokenStatus !== null && (
            <Stack gap={4}>
              <Text size="xs" fw={600} c="dimmed">
                Access token
              </Text>
              <Text size="sm">
                {tokenStatus.state === "expired" ? "Expired" : "Expires"} {formatExpiry(tokenStatus.expires_at)}
              </Text>
            </Stack>
          )}
        </SimpleGrid>

        <Stack gap="xs">
          <Group justify="space-between" align="center">
            <Text size="sm" fw={600}>
              Granted scopes
            </Text>
            {tokenStatus !== null && scopes.drift && (
              <Badge color="orange" variant="light">
                Scope drift
              </Badge>
            )}
          </Group>
          <Table.ScrollContainer minWidth={360}>
            <Table withTableBorder>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th>Scope</Table.Th>
                  <Table.Th ta="center">Requested</Table.Th>
                  <Table.Th ta="center">Granted</Table.Th>
                </Table.Tr>
              </Table.Thead>
              <Table.Tbody>
                {scopes.rows.length === 0 ? (
                  <Table.Tr>
                    <Table.Td colSpan={3}>
                      <Text size="sm" style={{ fontStyle: "italic" }} c="dimmed">
                        No scopes
                      </Text>
                    </Table.Td>
                  </Table.Tr>
                ) : (
                  scopes.rows.map((row) => (
                    <Table.Tr key={row.scope}>
                      <Table.Td>
                        <Text size="sm" ff="monospace" style={{ overflowWrap: "anywhere" }}>
                          {row.scope}
                        </Text>
                      </Table.Td>
                      <Table.Td ta="center">
                        <Text fw={700} c={row.requested ? "green" : "dimmed"} aria-label={row.requested ? "yes" : "no"}>
                          {row.requested ? "✓" : "✕"}
                        </Text>
                      </Table.Td>
                      <Table.Td ta="center">
                        <Text fw={700} c={row.granted ? "green" : "dimmed"} aria-label={row.granted ? "yes" : "no"}>
                          {row.granted ? "✓" : "✕"}
                        </Text>
                      </Table.Td>
                    </Table.Tr>
                  ))
                )}
              </Table.Tbody>
            </Table>
          </Table.ScrollContainer>
          {tokenStatus !== null && scopes.drift && (
            <Alert color="orange" variant="light" title="Granted scopes differ from the request">
              <Stack gap={4}>
                {scopes.missing.length > 0 && (
                  <Text size="sm">
                    Missing: <Code>{scopes.missing.join(" ")}</Code>
                  </Text>
                )}
                {scopes.extra.length > 0 && (
                  <Text size="sm">
                    Extra: <Code>{scopes.extra.join(" ")}</Code>
                  </Text>
                )}
                <Text size="sm">Reconnect this provider to update its authorization.</Text>
              </Stack>
            </Alert>
          )}
          {tokenStatus?.state === "expired" && tokenStatus.last_refresh_error && (
            <Alert color="red" variant="light" title="Refresh error">
              <Box component="code" style={{ overflowWrap: "anywhere", whiteSpace: "pre-wrap" }}>
                {tokenStatus.last_refresh_error}
              </Box>
            </Alert>
          )}
        </Stack>
      </Stack>
    </Paper>
  );
}

export function OAuthProviders(): JSX.Element {
  const [providers, setProviders] = useState<OAuthProviderStatus[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    void getApiClient()
      .listOAuthProviders()
      .then((result) => {
        if (active) setProviders(result);
      })
      .catch((failure: unknown) => {
        if (active) setError(failure instanceof Error ? failure.message : String(failure));
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, []);

  return (
    <Stack gap="lg">
      <div>
        <Title order={2}>OAuth Providers</Title>
        <Text size="sm" c="dimmed" mt={4}>
          Connect accounts and review their granted permissions.
        </Text>
      </div>

      {loading && (
        <Group justify="center" py="xl">
          <Loader size="sm" />
          <Text c="dimmed">Loading providers…</Text>
        </Group>
      )}
      {!loading && error && (
        <Alert color="red" title="Failed to load providers" role="alert">
          {error}
        </Alert>
      )}
      {!loading && !error && providers.length === 0 && (
        <Paper withBorder radius="md" p="lg">
          <Text c="dimmed">No OAuth providers configured.</Text>
        </Paper>
      )}
      {!loading && !error && providers.map((provider) => <ProviderCard key={provider.name} provider={provider} />)}
    </Stack>
  );
}
