// props/frontend/src/components/stats/SummaryCards.tsx
import { Card, SimpleGrid, Text } from "@mantine/core";
import type { OverviewResponse, DefinitionRow, StatsWithCI } from "../../lib/types";
import { formatStatsWithCI } from "../../lib/formatters";
import DefinitionIdLink from "../../lib/DefinitionIdLink";

interface Props {
  data: OverviewResponse;
}

export default function SummaryCards({ data }: Props) {
  let bestDefinition: { definition: DefinitionRow; recallStats: StatsWithCI } | null = null;
  for (const definition of data.definitions) {
    const stats = definition.stats["valid"]?.["whole_snapshot"];
    const recallStats = stats?.recall_stats;
    if (recallStats != null && (!bestDefinition || recallStats.mean > bestDefinition.recallStats.mean)) {
      bestDefinition = { definition, recallStats };
    }
  }

  const statusCounts: Record<string, number> = {};
  for (const definition of data.definitions) {
    for (const splitStats of Object.values(definition.stats)) {
      for (const kindStats of Object.values(splitStats)) {
        if (kindStats?.status_counts) {
          for (const [status, count] of Object.entries(kindStats.status_counts)) {
            statusCounts[status] = (statusCounts[status] ?? 0) + (count ?? 0);
          }
        }
      }
    }
  }
  const totalRuns = Object.values(statusCounts).reduce((sum, count) => sum + count, 0);

  return (
    <SimpleGrid cols={{ base: 1, md: 3 }} spacing="md" mb="lg">
      <Card shadow="sm" padding="md" radius="md" className="bg-white dark:bg-gray-900 dark:shadow-gray-950/30">
        <Text size="sm" fw={500} c="dimmed" mb="xs">
          Definitions
        </Text>
        <Text size="xl" fw={700}>
          {data.definitions.length}
        </Text>
        <Text size="xs" c="dimmed" mt={4}>
          Critic definitions
        </Text>
      </Card>

      <Card shadow="sm" padding="md" radius="md" className="bg-white dark:bg-gray-900 dark:shadow-gray-950/30">
        <Text size="sm" fw={500} c="dimmed" mb="xs">
          Best (Valid Whole)
        </Text>
        {bestDefinition ? (
          <>
            <Text size="xl" fw={700} c="green">
              {formatStatsWithCI(bestDefinition.recallStats)}
            </Text>
            <Text size="xs" mt={4}>
              <DefinitionIdLink id={bestDefinition.definition.image_digest} />
            </Text>
          </>
        ) : (
          <>
            <Text size="xl" fw={700} c="dimmed">
              -
            </Text>
            <Text size="xs" c="dimmed" mt={4}>
              No valid runs yet
            </Text>
          </>
        )}
      </Card>

      <Card shadow="sm" padding="md" radius="md" className="bg-white dark:bg-gray-900 dark:shadow-gray-950/30">
        <Text size="sm" fw={500} c="dimmed" mb="xs">
          Runs ({totalRuns})
        </Text>
        <div className="flex gap-2 text-xs">
          {statusCounts["exited"] ? (
            <span className="text-green-600 dark:text-green-400" title="Exited">
              ✓{statusCounts["exited"]}
            </span>
          ) : null}
          {statusCounts["in_progress"] ? (
            <span className="text-blue-600 dark:text-blue-400" title="In Progress">
              ⟳{statusCounts["in_progress"]}
            </span>
          ) : null}
          {statusCounts["timed_out"] ? (
            <span className="text-yellow-600 dark:text-yellow-400" title="Timed Out">
              T{statusCounts["timed_out"]}
            </span>
          ) : null}
        </div>
      </Card>
    </SimpleGrid>
  );
}

// props/frontend/src/components/stats/SummaryCards.svelte
<script lang="ts">
  import type { OverviewResponse, DefinitionRow, StatsWithCI } from "../../lib/types";
  import { formatStatsWithCI } from "../../lib/formatters";
  import DefinitionIdLink from "../../lib/DefinitionIdLink.svelte";

  interface Props {
    data: OverviewResponse;
  }

  const { data }: Props = $props();

  // Find best definition by valid whole-snapshot recall (preserves full StatsWithCI)
  function findBestDefinition(): { def: DefinitionRow; recall_stats: StatsWithCI } | null {
    let best: { def: DefinitionRow; recall_stats: StatsWithCI } | null = null;
    for (const def of data.definitions) {
      const stats = def.stats["valid"]?.["whole_snapshot"];
      const recall_stats = stats?.recall_stats;
      if (recall_stats != null) {
        if (!best || recall_stats.mean > best.recall_stats.mean) {
          best = { def, recall_stats };
        }
      }
    }
    return best;
  }

  // Aggregate status counts across all definitions
  function aggregateStatusCounts(): Record<string, number> {
    const counts: Record<string, number> = {};
    for (const def of data.definitions) {
      for (const splitStats of Object.values(def.stats)) {
        for (const kindStats of Object.values(splitStats)) {
          if (kindStats?.status_counts) {
            for (const [status, count] of Object.entries(kindStats.status_counts)) {
              counts[status] = (counts[status] ?? 0) + (count ?? 0);
            }
          }
        }
      }
    }
    return counts;
  }

  const bestDef = $derived(findBestDefinition());
  const statusCounts = $derived(aggregateStatusCounts());
  const totalRuns = $derived(Object.values(statusCounts).reduce((a, b) => a + b, 0));
</script>

<div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
  <!-- Definitions count -->
  <div class="bg-white dark:bg-gray-900 rounded-lg shadow dark:shadow-gray-950/30 p-4">
    <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">Definitions</h3>
    <div class="text-2xl font-bold">{data.definitions.length}</div>
    <div class="text-xs text-gray-500 dark:text-gray-400 mt-1">Critic definitions</div>
  </div>

  <!-- Best definition -->
  <div class="bg-white dark:bg-gray-900 rounded-lg shadow dark:shadow-gray-950/30 p-4">
    <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">Best (Valid Whole)</h3>
    {#if bestDef}
      <div class="text-2xl font-bold text-green-600 dark:text-green-400">{formatStatsWithCI(bestDef.recall_stats)}</div>
      <div class="text-xs mt-1">
        <DefinitionIdLink id={bestDef.def.image_digest} />
      </div>
    {:else}
      <div class="text-2xl font-bold text-gray-400 dark:text-gray-500">-</div>
      <div class="text-xs text-gray-500 dark:text-gray-400 mt-1">No valid runs yet</div>
    {/if}
  </div>

  <!-- Run status breakdown -->
  <div class="bg-white dark:bg-gray-900 rounded-lg shadow dark:shadow-gray-950/30 p-4">
    <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400 mb-2">Runs ({totalRuns})</h3>
    <div class="flex gap-2 text-xs">
      {#if statusCounts["exited"]}
        <span class="text-green-600 dark:text-green-400" title="Exited">
          ✓{statusCounts["exited"]}
        </span>
      {/if}
      {#if statusCounts["in_progress"]}
        <span class="text-blue-600 dark:text-blue-400" title="In Progress">
          ⟳{statusCounts["in_progress"]}
        </span>
      {/if}
      {#if statusCounts["timed_out"]}
        <span class="text-yellow-600 dark:text-yellow-400" title="Timed Out">
          T{statusCounts["timed_out"]}
        </span>
      {/if}
    </div>
  </div>
</div>
