// props/frontend/src/pages/DefinitionDetailPage.tsx
import { useEffect, useState } from "react";

import { Center, Loader, Text } from "@mantine/core";

import DefinitionDetail from "$components/DefinitionDetail";
import { fetchDefinitionDetail, type DefinitionDetailResponse } from "$lib/api/client";

interface Props {
  definitionId: string;
}

export default function DefinitionDetailPage({ definitionId }: Props) {
  const [definition, setDefinition] = useState<DefinitionDetailResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!definitionId) {
      setLoading(false);
      return;
    }

    let current = true;
    setLoading(true);
    setError(null);

    void fetchDefinitionDetail(definitionId)
      .then((data) => {
        if (current) setDefinition(data);
      })
      .catch((reason: unknown) => {
        if (current) setError(reason instanceof Error ? reason.message : "Failed to load definition");
      })
      .finally(() => {
        if (current) setLoading(false);
      });

    return () => {
      current = false;
    };
  }, [definitionId]);

  if (loading) {
    return (
      <Center mih={160}>
        <Loader size="sm" />
        <Text c="dimmed">Loading...</Text>
      </Center>
    );
  }
  if (error) return <Text c="red">{error}</Text>;
  if (definition) return <DefinitionDetail data={definition} />;
  return null;
}

// props/frontend/src/pages/DefinitionDetailPage.svelte
<script lang="ts">
  import DefinitionDetail from "$components/DefinitionDetail.svelte";
  import { fetchDefinitionDetail, type DefinitionDetailResponse } from "$lib/api/client";

  interface Props {
    definitionId: string;
  }
  const { definitionId }: Props = $props();

  let definition: DefinitionDetailResponse | null = $state(null);
  let loading = $state(true);
  let error: string | null = $state(null);

  async function loadData() {
    loading = true;
    error = null;
    try {
      definition = await fetchDefinitionDetail(definitionId);
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load definition";
    } finally {
      loading = false;
    }
  }

  // $effect runs immediately on mount and re-runs when definitionId changes
  $effect(() => {
    if (definitionId) {
      loadData();
    }
  });
</script>

{#if loading}
  <div class="flex items-center justify-center py-12">
    <div class="text-gray-500 dark:text-gray-400">Loading...</div>
  </div>
{:else if error}
  <div
    class="bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800 rounded p-4 text-red-700 dark:text-red-300"
  >
    {error}
  </div>
{:else if definition}
  <DefinitionDetail data={definition} />
{/if}
