// props/specimens/ducktape/2026-05-20-00/code/props/frontend/src/pages/ExamplesPage.svelte
<script lang="ts">
  import { searchParams } from "$lib/router";
  import ExampleDetail from "$components/ExampleDetail.svelte";
  import { fetchExampleDetail, type ExampleDetailResponse, type ExampleKind } from "$lib/api/client";

  interface Props {
    initialData?: ExampleDetailResponse;
  }

  let { initialData }: Props = $props();

  // svelte-ignore state_referenced_locally
  let example: ExampleDetailResponse | null = $state(initialData ?? null);
  // svelte-ignore state_referenced_locally
  let loading = $state(!initialData);
  let error: string | null = $state(null);

  const snapshotSlug = $derived($searchParams.get("snapshot_slug") ?? "");
  const exampleKind = $derived(($searchParams.get("example_kind") ?? "whole_snapshot") as ExampleKind);
  const filesHash = $derived($searchParams.get("files_hash"));

  async function loadData(slug: string, kind: ExampleKind, hash: string | null) {
    loading = true;
    error = null;
    try {
      example = await fetchExampleDetail(slug, kind, hash);
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load example";
    } finally {
      loading = false;
    }
  }

  // $effect runs immediately on mount and re-runs when any query param changes
  $effect(() => {
    if (snapshotSlug && !initialData) {
      loadData(snapshotSlug, exampleKind, filesHash);
    } else if (!snapshotSlug) {
      error = "Missing snapshot_slug parameter";
      loading = false;
    }
  });
</script>

{#if loading}
  <div class="flex items-center justify-center py-12">
    <div class="text-gray-500 dark:text-gray-400">Loading...</div>
  </div>
{:else if error}
  <p class="text-gray-500 dark:text-gray-400">{error}</p>
{:else if example}
  <ExampleDetail data={example} />
{/if}

// props/frontend/src/pages/ExamplesPage.tsx
import { useEffect, useState } from "react";

import { Center, Loader, Text } from "@mantine/core";

import ExampleDetail from "$components/ExampleDetail";
import { useSearchParams } from "$lib/router";
import { fetchExampleDetail, type ExampleDetailResponse, type ExampleKind } from "$lib/api/client";

interface Props {
  initialData?: ExampleDetailResponse;
}

export default function ExamplesPage({ initialData }: Props) {
  const searchParams = useSearchParams();
  const snapshotSlug = searchParams.get("snapshot_slug") ?? "";
  const exampleKind = (searchParams.get("example_kind") ?? "whole_snapshot") as ExampleKind;
  const filesHash = searchParams.get("files_hash");

  const [example, setExample] = useState<ExampleDetailResponse | null>(initialData ?? null);
  const [loading, setLoading] = useState(!initialData);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!snapshotSlug) {
      setError("Missing snapshot_slug parameter");
      setLoading(false);
      return;
    }
    if (initialData) return;

    let current = true;
    setLoading(true);
    setError(null);
    void fetchExampleDetail(snapshotSlug, exampleKind, filesHash)
      .then((data) => {
        if (current) setExample(data);
      })
      .catch((reason: unknown) => {
        if (current) setError(reason instanceof Error ? reason.message : "Failed to load example");
      })
      .finally(() => {
        if (current) setLoading(false);
      });

    return () => {
      current = false;
    };
  }, [snapshotSlug, exampleKind, filesHash, initialData]);

  if (loading) {
    return (
      <Center mih={160}>
        <Loader size="sm" />
        <Text c="dimmed">Loading...</Text>
      </Center>
    );
  }
  if (error) return <Text c="dimmed">{error}</Text>;
  if (example) return <ExampleDetail data={example} />;
  return null;
}
