// props/frontend/src/pages/OverviewPage.tsx
import { useEffect, useRef, useState } from "react";

import { Button, Card, Center, Group, Loader, SimpleGrid, Stack, Tabs, Text, Title } from "@mantine/core";

import CoverageHeatmap from "$components/stats/CoverageHeatmap";
import DefinitionsTable from "$components/stats/DefinitionsTable";
import DistributionChart from "$components/stats/DistributionChart";
import SummaryCards from "$components/stats/SummaryCards";
import { goto } from "$lib/router";
import { useRunModal } from "$lib/runModalContext";
import { toast } from "$lib/toast";
import type { RunModalPrefill } from "$lib/types";
import { fetchCoverage, fetchOverview, type CoverageResponse, type OverviewResponse } from "$lib/api/client";

interface Props {
  initialData?: OverviewResponse;
}

export default function OverviewPage({ initialData }: Props) {
  const runModal = useRunModal();
  const [overview, setOverview] = useState<OverviewResponse | null>(initialData ?? null);
  const [loading, setLoading] = useState(!initialData);
  const [error, setError] = useState<string | null>(null);
  const [analysisSplit, setAnalysisSplit] = useState<"valid" | "train">("valid");
  const [coverage, setCoverage] = useState<CoverageResponse | null>(null);
  const [analysisLoading, setAnalysisLoading] = useState(false);
  const analysisRequestId = useRef(0);

  useEffect(() => {
    if (initialData) return;

    let current = true;
    setLoading(true);
    setError(null);
    void fetchOverview()
      .then((data) => {
        if (current) setOverview(data);
      })
      .catch((reason: unknown) => {
        if (current) setError(reason instanceof Error ? reason.message : "Failed to load overview");
      })
      .finally(() => {
        if (current) setLoading(false);
      });

    return () => {
      current = false;
    };
  }, [initialData]);

  useEffect(() => {
    if (!overview) return;
    const requestId = ++analysisRequestId.current;
    setAnalysisLoading(true);

    void fetchCoverage(analysisSplit)
      .then((data) => {
        if (requestId === analysisRequestId.current) setCoverage(data);
      })
      .catch((reason: unknown) => {
        if (requestId === analysisRequestId.current) {
          toast.error(reason instanceof Error ? reason.message : "Failed to load analysis");
        }
      })
      .finally(() => {
        if (requestId === analysisRequestId.current) setAnalysisLoading(false);
      });

    return () => {
      analysisRequestId.current += 1;
    };
  }, [overview, analysisSplit]);

  function handleNavigateToRuns(filters: RunModalPrefill) {
    const params = new URLSearchParams();
    if (filters.definitionId) params.set("definition", filters.definitionId);
    if (filters.split) params.set("split", filters.split);
    if (filters.kind) params.set("kind", filters.kind);
    const query = params.toString();
    goto(query ? `/runs?${query}` : "/runs");
  }

  if (loading) {
    return (
      <Center mih={160}>
        <Loader size="sm" />
        <Text c="dimmed">Loading...</Text>
      </Center>
    );
  }
  if (error) return <Text c="red">{error}</Text>;
  if (!overview) return null;

  return (
    <Stack gap="md">
      <SummaryCards data={overview} />
      <Group justify="flex-end">
        <Button onClick={() => runModal.open()}>+ New Run</Button>
      </Group>
      <Card shadow="sm" radius="md" p={0}>
        <DefinitionsTable
          definitions={overview.definitions}
          exampleCounts={overview.example_counts}
          onCellClick={handleNavigateToRuns}
        />
      </Card>
      <Card shadow="sm" radius="md" p="md">
        <Group justify="space-between" mb="md">
          <Title order={3}>Stats &amp; Analysis</Title>
          <Tabs value={analysisSplit} onChange={(value) => value && setAnalysisSplit(value as "valid" | "train")}>
            <Tabs.List>
              <Tabs.Tab value="valid">Valid</Tabs.Tab>
              <Tabs.Tab value="train">Train</Tabs.Tab>
            </Tabs.List>
          </Tabs>
        </Group>

        {analysisLoading ? (
          <Center mih={100}>
            <Loader size="sm" />
            <Text c="dimmed">Loading analysis...</Text>
          </Center>
        ) : coverage ? (
          <Stack gap="md">
            <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="md">
              <DistributionChart
                values={coverage.max_recall_values}
                title="Max Recall Distribution"
                numBuckets={10}
                valueFormat={(value) => `${(value * 100).toFixed(0)}%`}
                color="rgb(59, 130, 246)"
              />
              <DistributionChart
                values={coverage.tp_count_values}
                title="TP Occurrence Count Distribution"
                numBuckets={8}
                valueFormat={(value) => value.toFixed(0)}
                color="rgb(34, 197, 94)"
              />
            </SimpleGrid>
            {coverage.definitions.length > 0 && (
              <CoverageHeatmap definitions={coverage.definitions} examples={coverage.examples} cells={coverage.cells} />
            )}
          </Stack>
        ) : null}
      </Card>
    </Stack>
  );
}

// props/frontend/src/pages/OverviewPage.svelte
<script lang="ts">
  import { onMount, getContext } from "svelte";
  import { SvelteURLSearchParams } from "svelte/reactivity";
  import { goto } from "$lib/router";
  import type { RunModalPrefill } from "$lib/types";
  import { fetchOverview, fetchCoverage, type OverviewResponse, type CoverageResponse } from "$lib/api/client";
  import DefinitionsTable from "$components/stats/DefinitionsTable.svelte";
  import SummaryCards from "$components/stats/SummaryCards.svelte";
  import DistributionChart from "$components/stats/DistributionChart.svelte";
  import CoverageHeatmap from "$components/stats/CoverageHeatmap.svelte";
  import TabButton from "$components/TabButton.svelte";
  import { toast } from "svelte-sonner";

  const runModal = getContext<{ open: (_?: RunModalPrefill) => void }>("runModal");

  interface Props {
    initialData?: OverviewResponse;
  }

  const { initialData }: Props = $props();

  // svelte-ignore state_referenced_locally
  let overview: OverviewResponse | null = $state(initialData ?? null);
  // svelte-ignore state_referenced_locally
  let loading = $state(!initialData);
  let error: string | null = $state(null);

  let analysisSplit: "valid" | "train" = $state("valid");
  let coverage: CoverageResponse | null = $state(null);
  let analysisLoading = $state(false);

  let analysisRequestId = 0;

  async function loadAnalysis(split: "valid" | "train") {
    const requestId = ++analysisRequestId;
    analysisLoading = true;
    try {
      const cov = await fetchCoverage(split);
      // Guard against stale responses from rapid split switching
      if (requestId === analysisRequestId) {
        coverage = cov;
      }
    } catch (e) {
      if (requestId === analysisRequestId) {
        toast.error(e instanceof Error ? e.message : "Failed to load analysis");
      }
    } finally {
      if (requestId === analysisRequestId) {
        analysisLoading = false;
      }
    }
  }

  $effect(() => {
    if (overview) {
      loadAnalysis(analysisSplit);
    }
  });

  async function loadData() {
    loading = true;
    error = null;
    try {
      overview = await fetchOverview();
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load overview";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    if (!initialData) {
      loadData();
    }
  });

  function handleNavigateToRuns(filters: RunModalPrefill) {
    const params = new SvelteURLSearchParams();
    if (filters.definitionId) params.set("definition", filters.definitionId);
    if (filters.split) params.set("split", filters.split);
    if (filters.kind) params.set("kind", filters.kind);
    const qs = params.toString();
    goto(qs ? `/runs?${qs}` : "/runs");
  }
</script>

{#if loading}
  <div class="flex items-center justify-center py-12">
    <div class="text-gray-500 dark:text-gray-400">Loading...</div>
  </div>
{:else if error}
  <div
    class="bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800 rounded p-4 text-red-700 dark:text-red-300"
  >
    {error}
  </div>
{:else if overview}
  <div>
    <SummaryCards data={overview} />
    <div class="flex justify-end mb-3">
      <button
        type="button"
        class="px-3 py-1 text-sm bg-blue-500 text-white rounded hover:bg-blue-600"
        onclick={() => runModal?.open()}
      >
        + New Run
      </button>
    </div>
    <div class="bg-white dark:bg-gray-900 rounded-lg shadow dark:shadow-gray-950/30">
      <DefinitionsTable
        definitions={overview.definitions}
        exampleCounts={overview.example_counts}
        onCellClick={handleNavigateToRuns}
      />
    </div>

    <!-- Analysis Section -->
    <div class="mt-4 bg-white dark:bg-gray-900 rounded-lg shadow dark:shadow-gray-950/30 p-4">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-lg font-semibold">Stats & Analysis</h3>
        <div class="flex border rounded dark:border-gray-700">
          <TabButton active={analysisSplit === "valid"} onclick={() => (analysisSplit = "valid")}>Valid</TabButton>
          <TabButton active={analysisSplit === "train"} onclick={() => (analysisSplit = "train")}>Train</TabButton>
        </div>
      </div>

      {#if analysisLoading}
        <div class="text-gray-500 dark:text-gray-400 text-center py-8">Loading analysis...</div>
      {:else if coverage}
        <div class="grid grid-cols-2 gap-4 mb-4">
          <DistributionChart
            values={coverage.max_recall_values}
            title="Max Recall Distribution"
            numBuckets={10}
            valueFormat={(v) => `${(v * 100).toFixed(0)}%`}
            color="rgb(59, 130, 246)"
          />
          <DistributionChart
            values={coverage.tp_count_values}
            title="TP Occurrence Count Distribution"
            numBuckets={8}
            valueFormat={(v) => `${v.toFixed(0)}`}
            color="rgb(34, 197, 94)"
          />
        </div>

        {#if coverage.definitions.length > 0}
          <CoverageHeatmap definitions={coverage.definitions} examples={coverage.examples} cells={coverage.cells} />
        {/if}
      {/if}
    </div>
  </div>
{/if}
