// props/frontend/src/pages/SnapshotDetailPage.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import {
  Badge,
  Box,
  Button,
  Card,
  Center,
  Code,
  Group,
  Loader,
  Paper,
  SimpleGrid,
  Stack,
  Tabs,
  Text,
  Title,
} from "@mantine/core";

import BackButton from "$components/BackButton";
import Breadcrumb from "$components/Breadcrumb";
import CopyButton from "$components/CopyButton";
import FileTree from "$components/FileTree";
import FileViewer from "$components/FileViewer";
import OccurrenceStats from "$components/stats/OccurrenceStats";
import CreditBadge from "$components/stats/CreditBadge";
import {
  fetchOccurrenceStats,
  fetchSnapshotClusters,
  fetchSnapshotDetail,
  fetchSnapshotFile,
  fetchSnapshotTree,
  type ClusterResponse,
  type FileContentResponse,
  type FileTreeResponse,
  type OccurrenceStatsRow,
  type SnapshotDetailResponse,
} from "$lib/api/client";
import { formatLocationAnchor } from "$lib/formatters";
import { useSearchParams, resolve } from "$lib/router";
import { toast } from "$lib/toast";
import OccurrenceLink from "$lib/OccurrenceLink";

interface Props {
  slug: string;
  initialSnapshot?: SnapshotDetailResponse;
  initialTree?: FileTreeResponse;
}

type ActiveTab = "files" | "tps" | "fps" | "clusters" | "stats";
type SnapshotIssue =
  SnapshotDetailResponse["true_positives"][number] | SnapshotDetailResponse["false_positives"][number];

function splitColor(split: string): string {
  switch (split) {
    case "train":
      return "blue";
    case "valid":
      return "green";
    case "test":
      return "violet";
    default:
      return "gray";
  }
}

export default function SnapshotDetailPage({ slug, initialSnapshot, initialTree }: Props) {
  const searchParams = useSearchParams();
  const parts = slug.split("/");
  const snapshotSlug = parts.slice(0, 2).join("/");
  const issueId = parts.length >= 4 ? parts[2] : undefined;
  const routeOccurrenceId = parts.length >= 4 ? parts[3] : undefined;
  const targetFile = searchParams.get("file") || undefined;

  const [snapshot, setSnapshot] = useState<SnapshotDetailResponse | null>(initialSnapshot ?? null);
  const [tree, setTree] = useState<FileTreeResponse | null>(initialTree ?? null);
  const [loading, setLoading] = useState(!initialSnapshot);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<ActiveTab>("files");
  const [selectedFile, setSelectedFile] = useState<FileContentResponse | null>(null);
  const [loadingFile, setLoadingFile] = useState(false);
  const [occurrenceStats, setOccurrenceStats] = useState<OccurrenceStatsRow[]>([]);
  const [clusters, setClusters] = useState<ClusterResponse[]>([]);
  const [expandedIssues, setExpandedIssues] = useState<Set<string>>(() => new Set());
  const [pendingScrollTarget, setPendingScrollTarget] = useState<string | null>(null);
  const fileRequestId = useRef(0);

  const occurrenceStatsMap = useMemo(
    () => new Map(occurrenceStats.map((occurrence) => [`${occurrence.tp_id}:${occurrence.occurrence_id}`, occurrence])),
    [occurrenceStats]
  );

  useEffect(() => {
    if (!snapshotSlug || initialSnapshot) return;

    let current = true;
    setLoading(true);
    setError(null);
    setOccurrenceStats([]);
    setClusters([]);
    setSelectedFile(null);
    setPendingScrollTarget(null);
    setExpandedIssues(new Set());
    fileRequestId.current += 1;
    setLoadingFile(false);

    void Promise.all([fetchSnapshotDetail(snapshotSlug), fetchSnapshotTree(snapshotSlug)])
      .then(([snapshotData, treeData]) => {
        if (!current) return;
        setSnapshot(snapshotData);
        setTree(treeData);

        void fetchOccurrenceStats(snapshotSlug).then(
          (data) => {
            if (current) setOccurrenceStats(data.occurrences);
          },
          (reason: unknown) => {
            if (current) toast.error(reason instanceof Error ? reason.message : "Failed to load occurrence stats");
          }
        );
        void fetchSnapshotClusters(snapshotSlug).then(
          (data) => {
            if (current) setClusters(data.clusters);
          },
          (reason: unknown) => {
            if (current) toast.error(reason instanceof Error ? reason.message : "Failed to load clusters");
          }
        );
      })
      .catch((reason: unknown) => {
        if (current) setError(reason instanceof Error ? reason.message : "Failed to load snapshot");
      })
      .finally(() => {
        if (current) setLoading(false);
      });

    return () => {
      current = false;
    };
  }, [snapshotSlug, initialSnapshot]);

  const handleFileClick = useCallback(
    async (path: string) => {
      const requestId = ++fileRequestId.current;
      const requestedSlug = snapshotSlug;
      setLoadingFile(true);
      try {
        const file = await fetchSnapshotFile(requestedSlug, path);
        if (requestId === fileRequestId.current) setSelectedFile(file);
      } catch (reason) {
        if (requestId === fileRequestId.current) toast.error(`Failed to load file: ${reason}`);
      } finally {
        if (requestId === fileRequestId.current) setLoadingFile(false);
      }
    },
    [snapshotSlug]
  );

  const toggleExpanded = useCallback((id: string) => {
    setExpandedIssues((current) => {
      const next = new Set(current);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const expandIssue = useCallback((id: string) => {
    setExpandedIssues((current) => (current.has(id) ? current : new Set(current).add(id)));
  }, []);

  const findAndNavigateToOccurrence = useCallback(
    (targetIssueId: string, occurrenceId: string, filePath?: string) => {
      if (!snapshot) return;
      const issues: SnapshotIssue[] = [...snapshot.true_positives, ...snapshot.false_positives];
      for (const issue of issues) {
        const currentIssueId = "tp_id" in issue ? issue.tp_id : issue.fp_id;
        if (currentIssueId !== targetIssueId) continue;
        const occurrence = issue.occurrences.find((item) => item.occurrence_id === occurrenceId);
        if (!occurrence?.locations.length) return;

        void handleFileClick(filePath || occurrence.locations[0].file);
        expandIssue(targetIssueId);
        setActiveTab("files");
        setPendingScrollTarget(`${targetIssueId}-${occurrenceId}`);
        return;
      }
    },
    [snapshot, handleFileClick, expandIssue]
  );

  useEffect(() => {
    if (issueId && routeOccurrenceId && snapshot) {
      findAndNavigateToOccurrence(issueId, routeOccurrenceId, targetFile);
    }
  }, [issueId, routeOccurrenceId, snapshot, targetFile, findAndNavigateToOccurrence]);

  useEffect(() => {
    if (!pendingScrollTarget || !selectedFile || loadingFile) return;
    const target = pendingScrollTarget;
    setPendingScrollTarget(null);
    const frame = requestAnimationFrame(() => {
      document.getElementById(target)?.scrollIntoView({ behavior: "smooth", block: "center" });
    });
    return () => cancelAnimationFrame(frame);
  }, [pendingScrollTarget, selectedFile, loadingFile]);

  const breadcrumbs = useMemo(() => {
    if (!selectedFile || !snapshot) return [{ label: snapshotSlug }];
    return [
      { label: snapshot.slug, href: `/snapshots/${snapshotSlug}` },
      ...selectedFile.path.split("/").map((part) => ({ label: part })),
    ];
  }, [selectedFile, snapshot, snapshotSlug]);

  function getOccurrenceUrl(targetIssueId: string, occurrenceId: string, filePath?: string): string {
    const routePath = `/snapshots/${snapshotSlug}/${targetIssueId}/${occurrenceId}`;
    const hashPath = resolve(routePath);
    if (filePath) return `${window.location.origin}${hashPath}?file=${encodeURIComponent(filePath)}`;
    return `${window.location.origin}${hashPath}`;
  }

  function renderIssueList(issues: SnapshotIssue[], isTruePositive: boolean) {
    if (issues.length === 0) {
      return <Text c="dimmed">No {isTruePositive ? "true" : "false"} positives</Text>;
    }

    return (
      <Stack gap="xs">
        {issues.map((issue) => {
          const currentIssueId = "tp_id" in issue ? issue.tp_id : issue.fp_id;
          const expanded = expandedIssues.has(currentIssueId);
          return (
            <Card key={currentIssueId} withBorder p={0}>
              <Button
                variant="subtle"
                color="gray"
                fullWidth
                onClick={() => toggleExpanded(currentIssueId)}
                aria-expanded={expanded}
              >
                <Group justify="space-between" w="100%">
                  <Group gap="xs">
                    <Text c="dimmed">{expanded ? "▼" : "▶"}</Text>
                    <Code>{currentIssueId}</Code>
                    <Text size="xs" c="dimmed">
                      ({issue.occurrences.length} occ)
                    </Text>
                  </Group>
                </Group>
              </Button>
              {expanded && (
                <Box px="md" pb="md">
                  <Box mt="xs">
                    <Text size="xs" fw={600} c="dimmed" tt="uppercase" mb={4}>
                      Rationale
                    </Text>
                    <Text size="sm" style={{ whiteSpace: "pre-wrap" }}>
                      {issue.rationale}
                    </Text>
                  </Box>
                  <Box mt="md">
                    <Text size="xs" fw={600} c="dimmed" tt="uppercase" mb={4}>
                      Occurrences
                    </Text>
                    <Stack gap="xs">
                      {issue.occurrences.map((occurrence) => {
                        const stats = isTruePositive
                          ? occurrenceStatsMap.get(`${currentIssueId}:${occurrence.occurrence_id}`)
                          : undefined;
                        const highlighted =
                          issueId === currentIssueId && routeOccurrenceId === occurrence.occurrence_id;
                        return (
                          <Paper
                            key={occurrence.occurrence_id}
                            id={`${currentIssueId}-${occurrence.occurrence_id}`}
                            withBorder
                            p="sm"
                            style={highlighted ? { outline: "2px solid var(--mantine-color-blue-5)" } : undefined}
                          >
                            <Group justify="space-between" align="flex-start">
                              <Group gap="xs">
                                <OccurrenceLink
                                  snapshotSlug={snapshot?.slug ?? snapshotSlug}
                                  issueId={currentIssueId}
                                  occurrenceId={occurrence.occurrence_id}
                                  filePath={occurrence.locations[0]?.file}
                                />
                                {stats && <CreditBadge meanCredit={stats.mean_credit} nRuns={stats.n_runs} />}
                              </Group>
                              <CopyButton
                                text={getOccurrenceUrl(
                                  currentIssueId,
                                  occurrence.occurrence_id,
                                  occurrence.locations[0]?.file
                                )}
                                label="Copy URL"
                              />
                            </Group>
                            <Stack gap={2} mt="xs">
                              {occurrence.locations.map((location, index) => (
                                <Text
                                  key={`${occurrence.occurrence_id}-${location.file}-${index}`}
                                  size="sm"
                                  ff="monospace"
                                >
                                  {formatLocationAnchor(location)}
                                  {location.note && (
                                    <Text span c="dimmed" fs="italic" ml="xs">
                                      ({location.note})
                                    </Text>
                                  )}
                                </Text>
                              ))}
                            </Stack>
                            {occurrence.note && (
                              <Text mt="xs" size="sm" c="dimmed" fs="italic">
                                {occurrence.note}
                              </Text>
                            )}
                            {isTruePositive &&
                              "critic_scopes_expected_to_recall" in occurrence &&
                              occurrence.critic_scopes_expected_to_recall &&
                              occurrence.critic_scopes_expected_to_recall.length > 0 && (
                                <Text mt="xs" size="xs" c="dimmed">
                                  Expected recall scopes:{" "}
                                  {occurrence.critic_scopes_expected_to_recall
                                    .map((scope: string[]) => scope.join(", "))
                                    .join(" | ")}
                                </Text>
                              )}
                            {!isTruePositive &&
                              "relevant_files" in occurrence &&
                              occurrence.relevant_files &&
                              occurrence.relevant_files.length > 0 && (
                                <Text mt="xs" size="xs" c="dimmed">
                                  Relevant: {occurrence.relevant_files.join(", ")}
                                </Text>
                              )}
                          </Paper>
                        );
                      })}
                    </Stack>
                  </Box>
                </Box>
              )}
            </Card>
          );
        })}
      </Stack>
    );
  }

  if (loading) {
    return (
      <Center mih={160}>
        <Loader size="sm" />
        <Text c="dimmed">Loading...</Text>
      </Center>
    );
  }
  if (error) return <Text c="red">{error}</Text>;
  if (!snapshot || !tree) return null;

  return (
    <Card shadow="sm" radius="md" p={0}>
      <Stack gap={0}>
        <Box p="md" style={{ borderBottom: "1px solid var(--mantine-color-default-border)" }}>
          <Group mb="xs">
            <BackButton href="/snapshots" />
            <Title order={2} ff="monospace">
              {snapshot.slug}
            </Title>
            <Badge color={splitColor(snapshot.split)} variant="light">
              {snapshot.split}
            </Badge>
          </Group>
          <Breadcrumb
            items={[{ label: "Home", href: "/" }, { label: "Snapshots", href: "/snapshots" }, { label: snapshot.slug }]}
          />
        </Box>

        <Tabs value={activeTab} onChange={(value) => value && setActiveTab(value as ActiveTab)} keepMounted={false}>
          <Tabs.List>
            <Tabs.Tab value="files">Files</Tabs.Tab>
            <Tabs.Tab value="tps">True Positives ({snapshot.true_positives.length})</Tabs.Tab>
            <Tabs.Tab value="fps">False Positives ({snapshot.false_positives.length})</Tabs.Tab>
            <Tabs.Tab value="clusters">Clusters ({clusters.length})</Tabs.Tab>
            <Tabs.Tab value="stats">Detection Stats</Tabs.Tab>
          </Tabs.List>

          <Box p="md">
            <Tabs.Panel value="files">
              <SimpleGrid cols={{ base: 1, lg: 2 }} spacing="md">
                <Box style={{ overflowY: "auto", maxHeight: "70vh" }}>
                  <Text size="sm" fw={600} mb="xs">
                    File Browser
                  </Text>
                  <FileTree nodes={tree.tree} onFileClick={handleFileClick} selectedPath={selectedFile?.path} />
                </Box>
                <Box style={{ overflowY: "auto", maxHeight: "70vh" }}>
                  {loadingFile ? (
                    <Center mih={160}>
                      <Loader size="sm" />
                      <Text c="dimmed">Loading...</Text>
                    </Center>
                  ) : selectedFile ? (
                    <>
                      <Box mb="sm">
                        <Breadcrumb items={breadcrumbs} />
                      </Box>
                      <FileViewer
                        file={selectedFile}
                        tps={snapshot.true_positives}
                        fps={snapshot.false_positives}
                        snapshotSlug={snapshot.slug}
                        targetOccurrenceId={routeOccurrenceId}
                      />
                    </>
                  ) : (
                    <Center mih={160}>
                      <Text c="dimmed">Select a file to view</Text>
                    </Center>
                  )}
                </Box>
              </SimpleGrid>
            </Tabs.Panel>

            <Tabs.Panel value="tps">
              <Box style={{ maxHeight: "70vh", overflowY: "auto" }}>
                {renderIssueList(snapshot.true_positives, true)}
              </Box>
            </Tabs.Panel>

            <Tabs.Panel value="fps">
              <Box style={{ maxHeight: "70vh", overflowY: "auto" }}>
                {renderIssueList(snapshot.false_positives, false)}
              </Box>
            </Tabs.Panel>

            <Tabs.Panel value="clusters">
              <Box style={{ maxHeight: "70vh", overflowY: "auto" }}>
                {clusters.length === 0 ? (
                  <Text c="dimmed">No clusters</Text>
                ) : (
                  <Stack gap="xs">
                    {clusters.map((cluster) => {
                      const expansionId = `cluster-${cluster.cluster_id}`;
                      const expanded = expandedIssues.has(expansionId);
                      return (
                        <Card key={cluster.cluster_id} withBorder p={0}>
                          <Button
                            variant="subtle"
                            color="gray"
                            fullWidth
                            onClick={() => toggleExpanded(expansionId)}
                            aria-expanded={expanded}
                          >
                            <Group justify="space-between" w="100%">
                              <Group gap="xs">
                                <Text c="dimmed">{expanded ? "▼" : "▶"}</Text>
                                <Code>{cluster.cluster_id}</Code>
                                <Text size="xs" c="dimmed">
                                  ({cluster.members.length} issues)
                                </Text>
                              </Group>
                            </Group>
                          </Button>
                          {expanded && (
                            <Box px="md" pb="md">
                              <Box mt="xs">
                                <Text size="xs" fw={600} c="dimmed" tt="uppercase" mb={4}>
                                  Description
                                </Text>
                                <Text size="sm" style={{ whiteSpace: "pre-wrap" }}>
                                  {cluster.rationale}
                                </Text>
                              </Box>
                              <Box mt="md">
                                <Text size="xs" fw={600} c="dimmed" tt="uppercase" mb={4}>
                                  Member Issues
                                </Text>
                                <Stack gap="xs">
                                  {cluster.members.map((member) => (
                                    <Paper
                                      key={`${member.critique_run_id}-${member.critique_issue_id}`}
                                      withBorder
                                      p="sm"
                                    >
                                      <Group gap="xs">
                                        <a
                                          href={resolve(`/runs/${member.critique_run_id}`)}
                                          style={{ fontFamily: "monospace" }}
                                        >
                                          {member.critique_run_id.slice(0, 8)}
                                        </a>
                                        <Text c="dimmed">/</Text>
                                        <Code>{member.critique_issue_id}</Code>
                                      </Group>
                                      {member.issue_rationale && (
                                        <Text mt="xs" size="sm">
                                          {member.issue_rationale}
                                        </Text>
                                      )}
                                      {member.rationale && (
                                        <Text mt="xs" size="xs" c="dimmed" fs="italic">
                                          {member.rationale}
                                        </Text>
                                      )}
                                    </Paper>
                                  ))}
                                </Stack>
                              </Box>
                            </Box>
                          )}
                        </Card>
                      );
                    })}
                  </Stack>
                )}
              </Box>
            </Tabs.Panel>

            <Tabs.Panel value="stats">
              <Box style={{ maxHeight: "70vh", overflowY: "auto" }}>
                <OccurrenceStats occurrences={occurrenceStats} />
              </Box>
            </Tabs.Panel>
          </Box>
        </Tabs>
      </Stack>
    </Card>
  );
}

// props/frontend/src/pages/SnapshotDetailPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { pathname, resolve } from "$lib/router";
  import { toast } from "svelte-sonner";
  import { splitBadgeClass } from "$lib/colors";
  import { formatLocationAnchor } from "$lib/formatters";
  import type { SnapshotDetailResponse, FileContentResponse, FileTreeResponse, ClusterResponse } from "$lib/api/client";
  import { fetchSnapshotDetail, fetchSnapshotTree, fetchSnapshotFile, fetchSnapshotClusters } from "$lib/api/client";
  import FileTree from "$components/FileTree.svelte";
  import FileViewer from "$components/FileViewer.svelte";
  import TabButton from "$components/TabButton.svelte";
  import Breadcrumb from "$components/Breadcrumb.svelte";
  import CopyButton from "$components/CopyButton.svelte";
  import BackButton from "$components/BackButton.svelte";
  import OccurrenceLink from "$lib/OccurrenceLink.svelte";
  import CreditBadge from "$components/stats/CreditBadge.svelte";
  import OccurrenceStats from "$components/stats/OccurrenceStats.svelte";
  import { fetchOccurrenceStats } from "$lib/api/client";
  import type { OccurrenceStatsRow } from "$lib/api/client";
  import { createExpansionState } from "$lib/expansionState.svelte";

  interface Props {
    slug: string; // This is the full catch-all path: "snapshot-name" or "snapshot-name/issueId/occurrenceId"
    initialSnapshot?: SnapshotDetailResponse;
    initialTree?: FileTreeResponse;
  }
  let { slug, initialSnapshot, initialTree }: Props = $props();

  // Parse the slug into components.
  // Snapshot slugs are "org/date" (2 parts), optionally followed by issueId/occurrenceId.
  const parsedSlug = $derived.by(() => {
    const parts = slug.split("/");
    const snapshotSlug = parts.slice(0, 2).join("/");
    const issueId = parts.length >= 4 ? parts[2] : undefined;
    const occurrenceId = parts.length >= 4 ? parts[3] : undefined;
    return { snapshotSlug, issueId, occurrenceId };
  });

  // Parse query params for file
  const queryParams = $derived.by(() => {
    const path = $pathname;
    const queryStart = path.indexOf("?");
    if (queryStart === -1) return new URLSearchParams();
    return new URLSearchParams(path.slice(queryStart + 1));
  });
  const targetFile = $derived(queryParams.get("file") || undefined);

  // svelte-ignore state_referenced_locally
  let snapshot: SnapshotDetailResponse | null = $state(initialSnapshot ?? null);
  // svelte-ignore state_referenced_locally
  let tree: FileTreeResponse | null = $state(initialTree ?? null);
  // svelte-ignore state_referenced_locally
  let loading = $state(!initialSnapshot);
  let error: string | null = $state(null);

  const expandedIssues = createExpansionState();
  let activeTab: "files" | "tps" | "fps" | "clusters" | "stats" = $state("files");
  let selectedFile: FileContentResponse | null = $state(null);
  let loadingFile = $state(false);
  let occurrenceStats: OccurrenceStatsRow[] = $state([]);
  let occurrenceStatsMap = $derived(new Map(occurrenceStats.map((o) => [`${o.tp_id}:${o.occurrence_id}`, o])));
  let clusters: ClusterResponse[] = $state([]);

  async function loadData() {
    loading = true;
    error = null;
    try {
      const [snapshotData, treeData] = await Promise.all([
        fetchSnapshotDetail(parsedSlug.snapshotSlug),
        fetchSnapshotTree(parsedSlug.snapshotSlug),
      ]);
      snapshot = snapshotData;
      tree = treeData;
      // Fetch occurrence stats and clusters (non-blocking)
      fetchOccurrenceStats(parsedSlug.snapshotSlug).then(
        (data) => {
          occurrenceStats = data.occurrences;
        },
        (e) => {
          toast.error(e instanceof Error ? e.message : "Failed to load occurrence stats");
        }
      );
      fetchSnapshotClusters(parsedSlug.snapshotSlug).then(
        (data) => {
          clusters = data.clusters;
        },
        (e) => {
          toast.error(e instanceof Error ? e.message : "Failed to load clusters");
        }
      );
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load snapshot";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    if (!initialSnapshot) {
      loadData();
    }
  });

  // Reload when slug changes
  $effect(() => {
    if (parsedSlug.snapshotSlug) {
      loadData();
    }
  });

  // Breadcrumb items for file viewer
  const breadcrumbs = $derived.by(() => {
    if (!selectedFile || !snapshot) return [{ label: parsedSlug.snapshotSlug }];

    const parts = selectedFile.path.split("/");
    const items: Array<{ label: string; href?: string }> = [
      { label: snapshot.slug, href: `/snapshots/${parsedSlug.snapshotSlug}` },
      ...parts.map((part) => ({ label: part })),
    ];

    return items;
  });

  async function handleFileClick(path: string) {
    loadingFile = true;
    try {
      selectedFile = await fetchSnapshotFile(parsedSlug.snapshotSlug, path);
    } catch (err) {
      toast.error(`Failed to load file: ${err}`);
    } finally {
      loadingFile = false;
    }
  }

  // Generate URL for occurrence
  function getOccurrenceUrl(issueId: string, occurrenceId: string, filePath?: string): string {
    const routePath = `/snapshots/${parsedSlug.snapshotSlug}/${issueId}/${occurrenceId}`;
    const hashPath = resolve(routePath);
    if (filePath) {
      return `${window.location.origin}/${hashPath}?file=${encodeURIComponent(filePath)}`;
    }
    return `${window.location.origin}/${hashPath}`;
  }

  function findAndNavigateToOccurrence(issueId: string, occurrenceId: string, filePath?: string) {
    if (!snapshot) return;
    const snap = snapshot; // Capture for closure

    const searchInIssues = (issues: typeof snap.true_positives | typeof snap.false_positives) => {
      for (const issue of issues) {
        const issueIdMatch = "tp_id" in issue ? issue.tp_id === issueId : issue.fp_id === issueId;
        if (issueIdMatch) {
          const occ = issue.occurrences.find((o) => o.occurrence_id === occurrenceId);
          if (occ?.locations.length) {
            // Use specified file or first file
            const fileToLoad = filePath || occ.locations[0].file;
            handleFileClick(fileToLoad);
            expandedIssues.expand(issueId);
            activeTab = "files";
            setTimeout(() => {
              document.getElementById(`${issueId}-${occurrenceId}`)?.scrollIntoView({
                behavior: "smooth",
                block: "center",
              });
            }, 100);
            return true;
          }
        }
      }
      return false;
    };

    searchInIssues(snap.true_positives) || searchInIssues(snap.false_positives);
  }

  // Handle deep linking via route params
  $effect(() => {
    if (parsedSlug.issueId && parsedSlug.occurrenceId && snapshot) {
      findAndNavigateToOccurrence(parsedSlug.issueId, parsedSlug.occurrenceId, targetFile);
    }
  });
</script>

{#if loading}
  <div class="flex items-center justify-center py-12">
    <div class="text-gray-500">Loading...</div>
  </div>
{:else if error}
  <div class="bg-red-50 border border-red-200 rounded p-4 text-red-700">
    {error}
  </div>
{:else if snapshot && tree}
  <div class="bg-white rounded-lg shadow">
    <!-- Header -->
    <div class="px-4 py-3 border-b">
      <div class="flex justify-between items-center mb-2">
        <div class="flex items-center gap-3">
          <BackButton href="/snapshots" />
          <h2 class="text-xl font-semibold font-mono">{snapshot.slug}</h2>
          <span class="px-2 py-1 text-xs font-medium rounded {splitBadgeClass(snapshot.split)}">
            {snapshot.split}
          </span>
        </div>
      </div>
      <Breadcrumb
        items={[{ label: "Home", href: "/" }, { label: "Snapshots", href: "/snapshots" }, { label: snapshot.slug }]}
      />
    </div>

    <!-- Tabs -->
    <div class="border-b">
      <nav class="flex -mb-px">
        <TabButton active={activeTab === "files"} onclick={() => (activeTab = "files")}>Files</TabButton>
        <TabButton active={activeTab === "tps"} onclick={() => (activeTab = "tps")}>
          True Positives ({snapshot.true_positives.length})
        </TabButton>
        <TabButton active={activeTab === "fps"} onclick={() => (activeTab = "fps")}>
          False Positives ({snapshot.false_positives.length})
        </TabButton>
        <TabButton active={activeTab === "clusters"} onclick={() => (activeTab = "clusters")}>
          Clusters ({clusters.length})
        </TabButton>
        <TabButton active={activeTab === "stats"} onclick={() => (activeTab = "stats")}>Detection Stats</TabButton>
      </nav>
    </div>

    <!-- Content -->
    <div class="p-4">
      {#if activeTab === "files"}
        <div class="grid grid-cols-2 gap-4">
          <!-- File Tree -->
          <div class="overflow-y-auto max-h-[70vh]">
            <h3 class="text-sm font-medium mb-2">File Browser</h3>
            <FileTree nodes={tree.tree} onFileClick={handleFileClick} selectedPath={selectedFile?.path} />
          </div>

          <!-- File Viewer -->
          <div class="overflow-y-auto max-h-[70vh]">
            {#if loadingFile}
              <div class="flex items-center justify-center h-full text-gray-500">Loading...</div>
            {:else if selectedFile}
              <div class="mb-3">
                <Breadcrumb items={breadcrumbs} />
              </div>
              <FileViewer
                file={selectedFile}
                tps={snapshot.true_positives}
                fps={snapshot.false_positives}
                snapshotSlug={snapshot.slug}
                targetOccurrenceId={parsedSlug.occurrenceId}
              />
            {:else}
              <div class="flex items-center justify-center h-full text-gray-500">Select a file to view</div>
            {/if}
          </div>
        </div>
      {:else if activeTab === "tps"}
        <div class="max-h-[70vh] overflow-y-auto">
          {#if snapshot.true_positives.length === 0}
            <p class="text-gray-500">No true positives</p>
          {:else}
            <div class="space-y-2">
              {#each snapshot.true_positives as tp (tp.tp_id)}
                <div class="border rounded">
                  <button
                    class="w-full px-3 py-2 flex justify-between items-center hover:bg-gray-50 text-left"
                    onclick={() => expandedIssues.toggle(tp.tp_id)}
                  >
                    <div class="flex items-center gap-2">
                      <span class="text-gray-400">{expandedIssues.isExpanded(tp.tp_id) ? "▼" : "▶"}</span>
                      <span class="font-mono text-sm font-medium">{tp.tp_id}</span>
                      <span class="text-xs text-gray-500">({tp.occurrences.length} occ)</span>
                    </div>
                  </button>

                  {#if expandedIssues.isExpanded(tp.tp_id)}
                    <div class="px-3 pb-3 border-t bg-gray-50">
                      <div class="mt-2">
                        <h4 class="text-xs font-medium text-gray-500 uppercase mb-1">Rationale</h4>
                        <p class="text-sm whitespace-pre-wrap">{tp.rationale}</p>
                      </div>
                      <div class="mt-3">
                        <h4 class="text-xs font-medium text-gray-500 uppercase mb-1">Occurrences</h4>
                        {#each tp.occurrences as occ (occ.occurrence_id)}
                          <div
                            id="{tp.tp_id}-{occ.occurrence_id}"
                            class="bg-white border rounded p-2 mt-1 {parsedSlug.occurrenceId === occ.occurrence_id
                              ? 'ring-2 ring-blue-500'
                              : ''}"
                          >
                            <div class="flex items-center justify-between">
                              <div class="flex items-center gap-2 text-xs">
                                <OccurrenceLink
                                  snapshotSlug={snapshot.slug}
                                  issueId={tp.tp_id}
                                  occurrenceId={occ.occurrence_id}
                                  filePath={occ.locations[0]?.file}
                                />
                                {#if occurrenceStatsMap.has(`${tp.tp_id}:${occ.occurrence_id}`)}
                                  {@const stats = occurrenceStatsMap.get(`${tp.tp_id}:${occ.occurrence_id}`)!}
                                  <CreditBadge meanCredit={stats.mean_credit} nRuns={stats.n_runs} />
                                {/if}
                              </div>
                              <CopyButton
                                text={getOccurrenceUrl(tp.tp_id, occ.occurrence_id, occ.locations[0]?.file)}
                                label="Copy URL"
                              />
                            </div>
                            <div class="mt-1">
                              {#each occ.locations as loc (`${occ.occurrence_id}-${loc.file}`)}
                                <div class="text-sm font-mono">
                                  {formatLocationAnchor(loc)}
                                  {#if loc.note}
                                    <span class="italic text-gray-500 ml-1">({loc.note})</span>
                                  {/if}
                                </div>
                              {/each}
                            </div>
                            {#if occ.note}
                              <div class="mt-1 text-sm text-gray-600 italic">{occ.note}</div>
                            {/if}
                            {#if occ.critic_scopes_expected_to_recall && occ.critic_scopes_expected_to_recall.length > 0}
                              <div class="mt-1 text-xs text-gray-500">
                                Expected recall scopes: {occ.critic_scopes_expected_to_recall
                                  .map((f: string[]) => f.join(", "))
                                  .join(" | ")}
                              </div>
                            {/if}
                          </div>
                        {/each}
                      </div>
                    </div>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}
        </div>
      {:else if activeTab === "fps"}
        <div class="max-h-[70vh] overflow-y-auto">
          {#if snapshot.false_positives.length === 0}
            <p class="text-gray-500">No false positives</p>
          {:else}
            <div class="space-y-2">
              {#each snapshot.false_positives as fp (fp.fp_id)}
                <div class="border rounded">
                  <button
                    class="w-full px-3 py-2 flex justify-between items-center hover:bg-gray-50 text-left"
                    onclick={() => expandedIssues.toggle(fp.fp_id)}
                  >
                    <div class="flex items-center gap-2">
                      <span class="text-gray-400">{expandedIssues.isExpanded(fp.fp_id) ? "▼" : "▶"}</span>
                      <span class="font-mono text-sm font-medium">{fp.fp_id}</span>
                      <span class="text-xs text-gray-500">({fp.occurrences.length} occ)</span>
                    </div>
                  </button>

                  {#if expandedIssues.isExpanded(fp.fp_id)}
                    <div class="px-3 pb-3 border-t bg-gray-50">
                      <div class="mt-2">
                        <h4 class="text-xs font-medium text-gray-500 uppercase mb-1">Rationale</h4>
                        <p class="text-sm whitespace-pre-wrap">{fp.rationale}</p>
                      </div>
                      <div class="mt-3">
                        <h4 class="text-xs font-medium text-gray-500 uppercase mb-1">Occurrences</h4>
                        {#each fp.occurrences as occ (occ.occurrence_id)}
                          <div
                            id="{fp.fp_id}-{occ.occurrence_id}"
                            class="bg-white border rounded p-2 mt-1 {parsedSlug.occurrenceId === occ.occurrence_id
                              ? 'ring-2 ring-blue-500'
                              : ''}"
                          >
                            <div class="flex items-center justify-between">
                              <div class="text-xs">
                                <OccurrenceLink
                                  snapshotSlug={snapshot.slug}
                                  issueId={fp.fp_id}
                                  occurrenceId={occ.occurrence_id}
                                  filePath={occ.locations[0]?.file}
                                />
                              </div>
                              <CopyButton
                                text={getOccurrenceUrl(fp.fp_id, occ.occurrence_id, occ.locations[0]?.file)}
                                label="Copy URL"
                              />
                            </div>
                            <div class="mt-1">
                              {#each occ.locations as loc (`${occ.occurrence_id}-${loc.file}`)}
                                <div class="text-sm font-mono">
                                  {formatLocationAnchor(loc)}
                                  {#if loc.note}
                                    <span class="italic text-gray-500 ml-1">({loc.note})</span>
                                  {/if}
                                </div>
                              {/each}
                            </div>
                            {#if occ.note}
                              <div class="mt-1 text-sm text-gray-600 italic">{occ.note}</div>
                            {/if}
                            {#if occ.relevant_files && occ.relevant_files.length > 0}
                              <div class="mt-1 text-xs text-gray-500">
                                Relevant: {occ.relevant_files.join(", ")}
                              </div>
                            {/if}
                          </div>
                        {/each}
                      </div>
                    </div>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}
        </div>
      {:else if activeTab === "clusters"}
        <div class="max-h-[70vh] overflow-y-auto">
          {#if clusters.length === 0}
            <p class="text-gray-500">No clusters</p>
          {:else}
            <div class="space-y-2">
              {#each clusters as cluster (cluster.cluster_id)}
                <div class="border rounded">
                  <button
                    class="w-full px-3 py-2 flex justify-between items-center hover:bg-gray-50 text-left"
                    onclick={() => expandedIssues.toggle(`cluster-${cluster.cluster_id}`)}
                  >
                    <div class="flex items-center gap-2">
                      <span class="text-gray-400"
                        >{expandedIssues.isExpanded(`cluster-${cluster.cluster_id}`) ? "▼" : "▶"}</span
                      >
                      <span class="font-mono text-sm font-medium">{cluster.cluster_id}</span>
                      <span class="text-xs text-gray-500">({cluster.members.length} issues)</span>
                    </div>
                  </button>

                  {#if expandedIssues.isExpanded(`cluster-${cluster.cluster_id}`)}
                    <div class="px-3 pb-3 border-t bg-gray-50">
                      <div class="mt-2">
                        <h4 class="text-xs font-medium text-gray-500 uppercase mb-1">Description</h4>
                        <p class="text-sm whitespace-pre-wrap">{cluster.rationale}</p>
                      </div>
                      <div class="mt-3">
                        <h4 class="text-xs font-medium text-gray-500 uppercase mb-1">Member Issues</h4>
                        {#each cluster.members as member (`${member.critique_run_id}-${member.critique_issue_id}`)}
                          <div class="bg-white border rounded p-2 mt-1">
                            <div class="flex items-center gap-2 text-xs">
                              <a
                                href="#{resolve(`/runs/${member.critique_run_id}`)}"
                                class="font-mono text-blue-600 hover:underline"
                              >
                                {member.critique_run_id.slice(0, 8)}
                              </a>
                              <span class="text-gray-400">/</span>
                              <span class="font-mono font-medium">{member.critique_issue_id}</span>
                            </div>
                            {#if member.issue_rationale}
                              <div class="mt-1 text-sm text-gray-700">{member.issue_rationale}</div>
                            {/if}
                            {#if member.rationale}
                              <div class="mt-1 text-xs text-gray-500 italic">{member.rationale}</div>
                            {/if}
                          </div>
                        {/each}
                      </div>
                    </div>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}
        </div>
      {:else if activeTab === "stats"}
        <div class="max-h-[70vh] overflow-y-auto">
          <OccurrenceStats occurrences={occurrenceStats} />
        </div>
      {/if}
    </div>
  </div>
{/if}
