// props/frontend/src/pages/SnapshotsPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { goto } from "$lib/router";
  import { fetchSnapshots, type SnapshotsResponse } from "$lib/api/client";
  import { splitBadgeClass } from "$lib/colors";

  interface Props {
    initialData?: SnapshotsResponse["snapshots"];
  }

  const { initialData }: Props = $props();

  // svelte-ignore state_referenced_locally
  let snapshots: SnapshotsResponse["snapshots"] = $state(initialData ?? []);
  // svelte-ignore state_referenced_locally
  let loading = $state(!initialData);
  let error: string | null = $state(null);

  async function loadData() {
    loading = true;
    error = null;
    try {
      const data = await fetchSnapshots();
      snapshots = data.snapshots;
    } catch (e) {
      error = e instanceof Error ? e.message : "Failed to load snapshots";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    if (!initialData) {
      loadData();
    }
  });

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString();
  }
</script>

{#if loading}
  <div class="flex items-center justify-center py-12">
    <div class="text-gray-500 dark:text-gray-400">Loading...</div>
  </div>
{:else if error}
  <div
    class="bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800 rounded p-4 text-red-700 dark:text-red-300"
  >
    {error}
  </div>
{:else}
  <div class="bg-white dark:bg-gray-900 rounded-lg shadow dark:shadow-gray-950/30 p-4">
    <h2 class="text-xl font-semibold mb-4">Snapshots</h2>

    {#if snapshots.length === 0}
      <p class="text-gray-500 dark:text-gray-400">No snapshots found</p>
    {:else}
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead class="bg-gray-50 dark:bg-gray-800">
            <tr>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Slug</th>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Split</th>
              <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">TPs</th>
              <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">FPs</th>
              <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase"
                >Created</th
              >
            </tr>
          </thead>
          <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
            {#each snapshots as snapshot (snapshot.slug)}
              <tr
                class="hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer"
                onclick={() => goto(`/snapshots/${snapshot.slug}`)}
              >
                <td class="px-4 py-2 font-mono text-sm">{snapshot.slug}</td>
                <td class="px-4 py-2">
                  <span class="px-2 py-1 text-xs font-medium rounded {splitBadgeClass(snapshot.split)}">
                    {snapshot.split}
                  </span>
                </td>
                <td class="px-4 py-2 text-right text-sm">{snapshot.tp_count}</td>
                <td class="px-4 py-2 text-right text-sm">{snapshot.fp_count}</td>
                <td class="px-4 py-2 text-right text-sm text-gray-500 dark:text-gray-400"
                  >{formatDate(snapshot.created_at)}</td
                >
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  </div>
{/if}

// props/frontend/src/pages/SnapshotsPage.tsx
import { useEffect, useState } from "react";

import { Badge, Card, Center, Loader, Table, Text, Title } from "@mantine/core";

import { goto } from "$lib/router";
import { fetchSnapshots, type SnapshotsResponse } from "$lib/api/client";

interface Props {
  initialData?: SnapshotsResponse["snapshots"];
}

function splitColor(split: string): string {
  switch (split) {
    case "train":
      return "blue";
    case "valid":
      return "green";
    case "test":
      return "violet";
    default:
      return "gray";
  }
}

export default function SnapshotsPage({ initialData }: Props) {
  const [snapshots, setSnapshots] = useState<SnapshotsResponse["snapshots"]>(initialData ?? []);
  const [loading, setLoading] = useState(!initialData);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (initialData) return;

    let current = true;
    setLoading(true);
    setError(null);
    void fetchSnapshots()
      .then((data) => {
        if (current) setSnapshots(data.snapshots);
      })
      .catch((reason: unknown) => {
        if (current) setError(reason instanceof Error ? reason.message : "Failed to load snapshots");
      })
      .finally(() => {
        if (current) setLoading(false);
      });

    return () => {
      current = false;
    };
  }, [initialData]);

  if (loading) {
    return (
      <Center mih={160}>
        <Loader size="sm" />
        <Text c="dimmed">Loading...</Text>
      </Center>
    );
  }
  if (error) return <Text c="red">{error}</Text>;

  return (
    <Card shadow="sm" radius="md" p="md">
      <Title order={2} mb="md">
        Snapshots
      </Title>
      {snapshots.length === 0 ? (
        <Text c="dimmed">No snapshots found</Text>
      ) : (
        <div style={{ overflowX: "auto" }}>
          <Table striped highlightOnHover verticalSpacing="sm" miw={640}>
            <Table.Thead>
              <Table.Tr>
                <Table.Th>Slug</Table.Th>
                <Table.Th>Split</Table.Th>
                <Table.Th ta="right">TPs</Table.Th>
                <Table.Th ta="right">FPs</Table.Th>
                <Table.Th ta="right">Created</Table.Th>
              </Table.Tr>
            </Table.Thead>
            <Table.Tbody>
              {snapshots.map((snapshot) => (
                <Table.Tr
                  key={snapshot.slug}
                  onClick={() => goto(`/snapshots/${snapshot.slug}`)}
                  style={{ cursor: "pointer" }}
                >
                  <Table.Td>
                    <Text ff="monospace" size="sm">
                      {snapshot.slug}
                    </Text>
                  </Table.Td>
                  <Table.Td>
                    <Badge color={splitColor(snapshot.split)} variant="light">
                      {snapshot.split}
                    </Badge>
                  </Table.Td>
                  <Table.Td ta="right">{snapshot.tp_count}</Table.Td>
                  <Table.Td ta="right">{snapshot.fp_count}</Table.Td>
                  <Table.Td ta="right">
                    <Text c="dimmed" size="sm">
                      {new Date(snapshot.created_at).toLocaleDateString()}
                    </Text>
                  </Table.Td>
                </Table.Tr>
              ))}
            </Table.Tbody>
          </Table>
        </div>
      )}
    </Card>
  );
}
